# Brings this package's content in from the web UI, where it is authored and built, and writes
# Strings.g.cs from en.json. Run it after an image, a font, a document or a key changes there.
#
#   assets/   <- <WebUI>/dist/assets  (images, flags, fonts, content) - the BUILT folder: the icon
#                font in it is cut to the icons both UIs name, by the web UI's own build
#                (build/icon-font-plugin.ts), so `npm run build` there comes first
#   Locales/  <- <WebUI>/src/locales/*.json - as authored; vhtranslator keeps them translated
#
# Both are mirrored (a file gone there is gone here) and committed: the package is built from this
# repo, and a clone with no web UI beside it still builds. assets/version.txt names the copy - the
# platforms that make a copy of the folder (Android) extract a version once, by it.
#
# Every file is read and written with an explicit UTF-8 encoding: Windows PowerShell would
# otherwise read these files as ANSI and double-encode every non-ASCII word in them.

$ErrorActionPreference = "Stop";

# <Vh>/VpnHood/src/AppLib/VpnHood.AppLib.Assets -> <Vh>
$vhFolder = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)));
$webUiDir = Join-Path $vhFolder "VpnHood.Client.WebUI";
$builtAssetsDir = Join-Path $webUiDir "dist\assets";
$localesDir = Join-Path $webUiDir "src\locales";
$assetsDir = Join-Path $PSScriptRoot "assets";
$targetLocalesDir = Join-Path $PSScriptRoot "Locales";
$stringsFile = Join-Path $PSScriptRoot "Strings.g.cs";
$utf8 = New-Object System.Text.UTF8Encoding($false);

if (!(Test-Path $builtAssetsDir)) { throw "The web UI has not been built beside this repo (npm run build in $webUiDir). $builtAssetsDir"; }
if (!(Test-Path $localesDir)) { throw "The web UI's locales are not beside this repo. $localesDir"; }

# ---- the files: a mirror of the built folder ----
$folders = @("images", "flags", "fonts", "content");
if (Test-Path $assetsDir) { Remove-Item $assetsDir -Recurse -Force; }
foreach ($folder in $folders) {
    $source = Join-Path $builtAssetsDir $folder;
    if (!(Test-Path $source)) { throw "The built assets folder has no '$folder' folder. $source"; }
    Copy-Item $source (Join-Path $assetsDir $folder) -Recurse;
}

# the name of this copy: one hash over every file's path and bytes, in a fixed order
$sha = [System.Security.Cryptography.SHA256]::Create();
$files = Get-ChildItem $assetsDir -Recurse -File | Sort-Object { $_.FullName.Substring($assetsDir.Length).Replace("\", "/") };
$stream = New-Object System.IO.MemoryStream;
foreach ($file in $files) {
    $relative = $file.FullName.Substring($assetsDir.Length + 1).Replace("\", "/");
    $nameBytes = $utf8.GetBytes($relative + "`n");
    $stream.Write($nameBytes, 0, $nameBytes.Length);
    $bytes = [System.IO.File]::ReadAllBytes($file.FullName);
    $stream.Write($bytes, 0, $bytes.Length);
}
$hash = [System.BitConverter]::ToString($sha.ComputeHash($stream.ToArray())).Replace("-", "").Substring(0, 16).ToLowerInvariant();
[System.IO.File]::WriteAllText((Join-Path $assetsDir "version.txt"), $hash, $utf8);
Write-Host "Copied $($files.Count) files to assets/ ($hash).";

# ---- the words: a mirror of the locale files ----
if (Test-Path $targetLocalesDir) { Remove-Item $targetLocalesDir -Recurse -Force; }
New-Item -ItemType Directory $targetLocalesDir | Out-Null;
$localeFiles = Get-ChildItem $localesDir -Filter "*.json";
foreach ($file in $localeFiles) { Copy-Item $file.FullName $targetLocalesDir; }
Write-Host "Copied $($localeFiles.Count) locale files to Locales/.";

# ---- Strings.g.cs: one member per key of en.json ----
$english = [System.IO.File]::ReadAllText((Join-Path $targetLocalesDir "en.json"), $utf8) | ConvertFrom-Json;

function Get-MemberName([string] $key) {
    $name = ($key -split "_" | ForEach-Object {
        if ($_.Length -eq 0) { "" }
        else { $_.Substring(0, 1).ToUpperInvariant() + $_.Substring(1).ToLowerInvariant() }
    }) -join "";
    # a key may start with a digit (24_7_SUPPORT); a member may not
    if ($name -match "^\d") { $name = "_" + $name; }
    return $name;
}

function Get-DocText([string] $text) {
    $line = ($text -replace "\s+", " ").Trim();
    if ($line.Length -gt 120) { $line = $line.Substring(0, 117) + "..."; }
    return $line.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}

$builder = New-Object System.Text.StringBuilder;
[void]$builder.AppendLine("// <auto-generated>");
[void]$builder.AppendLine("//     Written by _sync-assets.ps1 from Locales/en.json. Do not edit by hand:");
[void]$builder.AppendLine("//     the words live in the web UI's locale files, and this file follows them.");
[void]$builder.AppendLine("// </auto-generated>");
[void]$builder.AppendLine("");
[void]$builder.AppendLine("namespace VpnHood.AppLib.Assets;");
[void]$builder.AppendLine("");
[void]$builder.AppendLine("public sealed partial class Strings");
[void]$builder.AppendLine("{");

$names = @{};
$count = 0;
foreach ($property in $english.PSObject.Properties) {
    $key = $property.Name;
    $text = [string]$property.Value;
    $name = Get-MemberName $key;
    if ($names.ContainsKey($name)) { throw "Two keys make the same member name '$name': '$key' and '$($names[$name])'."; }
    $names[$name] = $key;

    # vue-i18n's named placeholders, in the order the text uses them
    $placeholders = @();
    foreach ($match in [regex]::Matches($text, "{([A-Za-z][A-Za-z0-9]*)}")) {
        if ($placeholders -notcontains $match.Groups[1].Value) { $placeholders += $match.Groups[1].Value; }
    }

    if ($count -gt 0) { [void]$builder.AppendLine(""); }
    [void]$builder.AppendLine("    /// <summary>$(Get-DocText $text)</summary>");
    if ($placeholders.Count -eq 0) {
        [void]$builder.AppendLine("    public string $name => Get(`"$key`");");
    }
    else {
        $parameters = ($placeholders | ForEach-Object { "object $_" }) -join ", ";
        $arguments = ($placeholders | ForEach-Object { "(`"$_`", $_)" }) -join ", ";
        [void]$builder.AppendLine("    public string $name($parameters) => Get(`"$key`", $arguments);");
    }
    $count++;
}

[void]$builder.AppendLine("}");
[System.IO.File]::WriteAllText($stringsFile, $builder.ToString(), (New-Object System.Text.UTF8Encoding($true)));
Write-Host "Wrote $count members to Strings.g.cs.";
