// <auto-generated>
//     Written by _sync-assets.ps1 from Locales/en.json. Do not edit by hand:
//     the words live in the web UI's locale files, and this file follows them.
// </auto-generated>

namespace VpnHood.AppLib.Assets;

public sealed partial class Strings
{
    /// <summary>System default</summary>
    public string SystemDefaultLanguage => Get("SYSTEM_DEFAULT_LANGUAGE");

    /// <summary>Your device language isn't supported; English will be displayed instead.</summary>
    public string SystemDefaultLanguageNotSupportedDesc => Get("SYSTEM_DEFAULT_LANGUAGE_NOT_SUPPORTED_DESC");

    /// <summary>Language</summary>
    public string Language => Get("LANGUAGE");

    /// <summary>VpnHood!</summary>
    public string EngineName => Get("ENGINE_NAME");

    /// <summary>VpnHood! CLIENT</summary>
    public string VpnHoodAppName => Get("VPN_HOOD_APP_NAME");

    /// <summary>VpnHood! CONNECT</summary>
    public string VpnHoodConnectAppName => Get("VPN_HOOD_CONNECT_APP_NAME");

    /// <summary>Settings</summary>
    public string Settings => Get("SETTINGS");

    /// <summary>Add</summary>
    public string Add => Get("ADD");

    /// <summary>Add list</summary>
    public string AddList => Get("ADD_LIST");

    /// <summary>Version</summary>
    public string Version => Get("VERSION");

    /// <summary>Connect</summary>
    public string Connect => Get("CONNECT");

    /// <summary>Initializing</summary>
    public string Initializing => Get("INITIALIZING");

    /// <summary>Connecting</summary>
    public string Connecting => Get("CONNECTING");

    /// <summary>Connected</summary>
    public string Connected => Get("CONNECTED");

    /// <summary>Disconnect</summary>
    public string Disconnect => Get("DISCONNECT");

    /// <summary>Disconnected</summary>
    public string Disconnected => Get("DISCONNECTED");

    /// <summary>Disconnecting</summary>
    public string Disconnecting => Get("DISCONNECTING");

    /// <summary>Stop Diagnosing</summary>
    public string StopDiagnosing => Get("STOP_DIAGNOSING");

    /// <summary>Finding best server</summary>
    public string FindingBestServer => Get("FINDING_BEST_SERVER");

    /// <summary>Finding network</summary>
    public string FindingNetwork => Get("FINDING_NETWORK");

    /// <summary>You are connected in diagnostic mode.</summary>
    public string ConnectedInDiagnosticMode => Get("CONNECTED_IN_DIAGNOSTIC_MODE");

    /// <summary>Diagnosing</summary>
    public string Diagnosing => Get("DIAGNOSING");

    /// <summary>Waiting</summary>
    public string Waiting => Get("WAITING");

    /// <summary>Unstable</summary>
    public string Unstable => Get("UNSTABLE");

    /// <summary>Add server</summary>
    public string AddServer => Get("ADD_SERVER");

    /// <summary>Add or remove servers</summary>
    public string AddOrRemoveServers => Get("ADD_OR_REMOVE_SERVERS");

    /// <summary>Diagnose</summary>
    public string Diagnose => Get("DIAGNOSE");

    /// <summary>Delete</summary>
    public string Remove => Get("REMOVE");

    /// <summary>Rename</summary>
    public string Rename => Get("RENAME");

    /// <summary>Cancel</summary>
    public string Cancel => Get("CANCEL");

    /// <summary>Skip</summary>
    public string Skip => Get("SKIP");

    /// <summary>Close</summary>
    public string Close => Get("CLOSE");

    /// <summary>Done</summary>
    public string Done => Get("DONE");

    /// <summary>Save</summary>
    public string Save => Get("SAVE");

    /// <summary>OK</summary>
    public string Ok => Get("OK");

    /// <summary>No Server</summary>
    public string NoServerSelected => Get("NO_SERVER_SELECTED");

    /// <summary>No Location</summary>
    public string NoLocationSelected => Get("NO_LOCATION_SELECTED");

    /// <summary>Server</summary>
    public string Server => Get("SERVER");

    /// <summary>Change Server</summary>
    public string ManageServers => Get("MANAGE_SERVERS");

    /// <summary>What's New?</summary>
    public string WhatsNew => Get("WHATS_NEW");

    /// <summary>Send Feedback</summary>
    public string SendFeedback => Get("SEND_FEEDBACK");

    /// <summary>https://docs.google.com/forms/d/e/1FAIpQLSd5AQesTSbDo23_4CkNiKmSPtPBaZIuFjAFnjqLo6XGKG5gyg/viewform?usp=sf_link</summary>
    public string SendFeedbackUrl => Get("SEND_FEEDBACK_URL");

    /// <summary>Create a Personal Server</summary>
    public string CreatePersonalServer => Get("CREATE_PERSONAL_SERVER");

    /// <summary>Open Report</summary>
    public string OpenReport => Get("OPEN_REPORT");

    /// <summary>Send Report</summary>
    public string SendReport => Get("SEND_REPORT");

    /// <summary>General</summary>
    public string General => Get("GENERAL");

    /// <summary>Do you really want to remove this server?</summary>
    public string ConfirmRemoveServer => Get("CONFIRM_REMOVE_SERVER");

    /// <summary>Add server key</summary>
    public string AddAccessKeyTitle => Get("ADD_ACCESS_KEY_TITLE");

    /// <summary>Copy and paste an server key to add a server.</summary>
    public string AddAccessKeySubtitle => Get("ADD_ACCESS_KEY_SUBTITLE");

    /// <summary>The serverKey has invalid format.</summary>
    public string InvalidAccessKeyFormat => Get("INVALID_ACCESS_KEY_FORMAT");

    /// <summary>Home</summary>
    public string Home => Get("HOME");

    /// <summary>Servers</summary>
    public string Servers => Get("SERVERS");

    /// <summary>Apps &amp; Domains</summary>
    public string AppsAndDomains => Get("APPS_AND_DOMAINS");

    /// <summary>Split Apps</summary>
    public string SplitApps => Get("SPLIT_APPS");

    /// <summary>Split Tunnel by App routes traffic inside or outside the VPN per app, allowing direct access where the VPN isn't need...</summary>
    public string SplitAppsDesc => Get("SPLIT_APPS_DESC");

    /// <summary>Choose which apps use the VPN and which connect directly.</summary>
    public string SplitAppsShortDesc => Get("SPLIT_APPS_SHORT_DESC");

    /// <summary>All apps are excluded, so no traffic will be tunneled. Enable at least one app.</summary>
    public string AllAppsExcludedErrorMsg => Get("ALL_APPS_EXCLUDED_ERROR_MSG");

    /// <summary>All</summary>
    public string All => Get("ALL");

    /// <summary>All Except {x}</summary>
    public string AllExceptX(object x) => Get("ALL_EXCEPT_X", ("x", x));

    /// <summary>Only {x}</summary>
    public string OnlyX(object x) => Get("ONLY_X", ("x", x));

    /// <summary>Countries</summary>
    public string Countries => Get("COUNTRIES");

    /// <summary>Split Countries</summary>
    public string SplitCountries => Get("SPLIT_COUNTRIES");

    /// <summary>Split Tunneling</summary>
    public string SplitCountriesTmp => Get("SPLIT_COUNTRIES_TMP");

    /// <summary>Split Tunnel by Country lets you route traffic through or outside the VPN based on destination country, allowing dire...</summary>
    public string SplitCountriesDesc => Get("SPLIT_COUNTRIES_DESC");

    /// <summary>Choose which countries use the VPN and which connect directly.</summary>
    public string SplitCountriesShortDesc => Get("SPLIT_COUNTRIES_SHORT_DESC");

    /// <summary>Exclude My Country</summary>
    public string ExcludeMyCountry => Get("EXCLUDE_MY_COUNTRY");

    /// <summary>Bypasses the VPN for local traffic. Best balance of speed and privacy for daily use.</summary>
    public string SplitExcludeMyCountryDesc => Get("SPLIT_EXCLUDE_MY_COUNTRY_DESC");

    /// <summary>Routes all traffic through the VPN. Maximize privacy, but local services and websites may load slower.</summary>
    public string SplitCountryOffDesc => Get("SPLIT_COUNTRY_OFF_DESC");

    /// <summary>All countries are excluded, so no traffic will be tunneled. Enable at least one country.</summary>
    public string AllCountriesExcludedErrorMsg => Get("ALL_COUNTRIES_EXCLUDED_ERROR_MSG");

    /// <summary>Faster</summary>
    public string Faster => Get("FASTER");

    /// <summary>Include all</summary>
    public string IncludeAll => Get("INCLUDE_ALL");

    /// <summary>All countries go through the VPN — no country is split out.</summary>
    public string IncludeAllDesc => Get("INCLUDE_ALL_DESC");

    /// <summary>Custom include list</summary>
    public string CustomIncludeList => Get("CUSTOM_INCLUDE_LIST");

    /// <summary>Routes only selected countries traffic through the VPN</summary>
    public string CustomIncludeListDesc => Get("CUSTOM_INCLUDE_LIST_DESC");

    /// <summary>Slower</summary>
    public string Slower => Get("SLOWER");

    /// <summary>Protocols</summary>
    public string Protocols => Get("PROTOCOLS");

    /// <summary>Protocol</summary>
    public string ProtocolTitle => Get("PROTOCOL_TITLE");

    /// <summary>A VPN protocol defines how data is transferred between your device and the VPN server after the initial connection is...</summary>
    public string ProtocolDesc => Get("PROTOCOL_DESC");

    /// <summary>UDP</summary>
    public string ProtocolUdp => Get("PROTOCOL_UDP");

    /// <summary>Lightweight protocol for faster connections, but access may be limited.</summary>
    public string ProtocolUdpDesc => Get("PROTOCOL_UDP_DESC");

    /// <summary>TCP</summary>
    public string ProtocolTcp => Get("PROTOCOL_TCP");

    /// <summary>Reliable protocol for better compatibility and stable connections.</summary>
    public string ProtocolTcpDesc => Get("PROTOCOL_TCP_DESC");

    /// <summary>QUIC</summary>
    public string ProtocolQuic => Get("PROTOCOL_QUIC");

    /// <summary>Modern protocol over UDP for faster, more reliable connections, but access may be restricted.</summary>
    public string ProtocolQuicDesc => Get("PROTOCOL_QUIC_DESC");

    /// <summary>Block QUIC</summary>
    public string ProtocolBlockQuic => Get("PROTOCOL_BLOCK_QUIC");

    /// <summary>Block QUIC so apps switch to standard streaming, which may improve video playback in Cloak Mode.</summary>
    public string ProtocolBlockQuicDesc => Get("PROTOCOL_BLOCK_QUIC_DESC");

    /// <summary>Cloak</summary>
    public string Cloak => Get("CLOAK");

    /// <summary>Cloak Mode</summary>
    public string CloakMode => Get("CLOAK_MODE");

    /// <summary>&lt;span class="text-promote-premium-color-premium"&gt;Cloak&lt;/span&gt; Mode</summary>
    public string CloakModeColored => Get("CLOAK_MODE_COLORED");

    /// <summary>Overcomes VPN blocks by disguising your VPN traffic as regular web traffic, making it resistant to deep packet inspec...</summary>
    public string CloakModeDesc1 => Get("CLOAK_MODE_DESC_1");

    /// <summary>Cloak mode ensures reliable access in restricted networks. This mode is exclusive to VpnHood.</summary>
    public string CloakModeDesc2 => Get("CLOAK_MODE_DESC_2");

    /// <summary>Overcomes VPN blocks by disguising your VPN traffic as regular web traffic.</summary>
    public string CloakModeShortDesc => Get("CLOAK_MODE_SHORT_DESC");

    /// <summary>Selected Apps</summary>
    public string SelectedApps => Get("SELECTED_APPS");

    /// <summary>A new server has been added.</summary>
    public string NewServerAdded => Get("NEW_SERVER_ADDED");

    /// <summary>Local Network</summary>
    public string LocalNetwork => Get("LOCAL_NETWORK");

    /// <summary>Split Local Network</summary>
    public string SplitLocalNetwork => Get("SPLIT_LOCAL_NETWORK");

    /// <summary>Allow access to local devices (e.g., TV, printer) by excluding local network traffic.</summary>
    public string SplitLocalNetworkDesc => Get("SPLIT_LOCAL_NETWORK_DESC");

    /// <summary>Allow access to local devices like printers and TVs.</summary>
    public string SplitLocalNetworkShortDesc => Get("SPLIT_LOCAL_NETWORK_SHORT_DESC");

    /// <summary>Split Domains</summary>
    public string SplitDomains => Get("SPLIT_DOMAINS");

    /// <summary>Include, exclude, or block specific domains from VPN traffic.</summary>
    public string SplitDomainsDesc => Get("SPLIT_DOMAINS_DESC");

    /// <summary>Choose which websites and domains use the VPN, bypass it, or are blocked.</summary>
    public string SplitDomainsShortDesc => Get("SPLIT_DOMAINS_SHORT_DESC");

    /// <summary>Create a Personal Server</summary>
    public string Createserver => Get("createServer");

    /// <summary>You disconnected another device because you used the same server key on multiple devices!</summary>
    public string SessionSuppressedToOther => Get("SESSION_SUPPRESSED_TO_OTHER");

    /// <summary>You have been disconnected because another device connected with your server key!</summary>
    public string SessionSuppressedByOther => Get("SESSION_SUPPRESSED_BY_OTHER");

    /// <summary>Your VpnHood app is deprecated and will stop working sooner or later! Consider upgrading as soon as possible.</summary>
    public string VersionIsDeprecated => Get("VERSION_IS_DEPRECATED");

    /// <summary>There is a new version available to install.</summary>
    public string VersionIsOld => Get("VERSION_IS_OLD");

    /// <summary>Install</summary>
    public string Install => Get("install");

    /// <summary>Ignore</summary>
    public string Ignore => Get("IGNORE");

    /// <summary>Later</summary>
    public string Later => Get("LATER");

    /// <summary>Update From Google Play</summary>
    public string UpdateFromGooglePlay => Get("UPDATE_FROM_GOOGLE_PLAY");

    /// <summary>Update from direct link</summary>
    public string UpdateFromDirectLink => Get("UPDATE_FROM_DIRECT_LINK");

    /// <summary>Update From Alternative link</summary>
    public string UpdateFromAlternativeLink => Get("UPDATE_FROM_ALTERNATIVE_LINK");

    /// <summary>Don't have access to Google Play?</summary>
    public string DoNotHaveAccessToGooglePlay => Get("DO_NOT_HAVE_ACCESS_TO_GOOGLE_PLAY");

    /// <summary>Use only if you do not have access to Google Play</summary>
    public string UpdateFromAlternativeLinkNotice => Get("UPDATE_FROM_ALTERNATIVE_LINK_NOTICE");

    /// <summary>Your Version:</summary>
    public string CurrentVersion => Get("CURRENT_VERSION");

    /// <summary>New Version:</summary>
    public string NewVersion => Get("NEW_VERSION");

    /// <summary>Go Premium</summary>
    public string GoPremium => Get("GO_PREMIUM");

    /// <summary>Get the deal</summary>
    public string GetTheDeal => Get("GET_THE_DEAL");

    /// <summary>Continue</summary>
    public string Continue => Get("CONTINUE");

    /// <summary>No</summary>
    public string No => Get("NO");

    /// <summary>Yes</summary>
    public string Yes => Get("YES");

    /// <summary>Recommended</summary>
    public string Recommended => Get("RECOMMENDED");

    /// <summary>of</summary>
    public string Of => Get("OF");

    /// <summary>On</summary>
    public string On => Get("ON");

    /// <summary>Off</summary>
    public string Off => Get("OFF");

    /// <summary>Error</summary>
    public string Error => Get("ERROR");

    /// <summary>Reconnect to apply your recent change.</summary>
    public string ReconnectRequiredMsg => Get("RECONNECT_REQUIRED_MSG");

    /// <summary>Reconnect</summary>
    public string Reconnect => Get("RECONNECT");

    /// <summary>Oooops!</summary>
    public string Oops => Get("OOPS");

    /// <summary>Unable to connect to the engine</summary>
    public string LoadAppErrorDesc => Get("LOAD_APP_ERROR_DESC");

    /// <summary>Reload</summary>
    public string ReloadApp => Get("RELOAD_APP");

    /// <summary>You haven’t added any servers yet. Please add a server by clicking on the "Add Server" button.</summary>
    public string NoServerAvailable => Get("NO_SERVER_AVAILABLE");

    /// <summary>&lt;h3 class="mb-3"&gt;Don’t have a Server Key?&lt;/h3&gt;&lt;p class="mb-2"&gt;You can acquire a server key through the following meth...</summary>
    public string GetServerKeyMethodsNoConnectDesc => Get("GET_SERVER_KEY_METHODS_NO_CONNECT_DESC");

    /// <summary>&lt;h3 class="mb-3"&gt;Don’t have a Server Key?&lt;/h3&gt;&lt;p class="mb-2"&gt;If you need a free VPN for personal use, consider &lt;a hr...</summary>
    public string GetServerKeyMethodsDesc(object connectAppUrl) => Get("GET_SERVER_KEY_METHODS_DESC", ("connectAppUrl", connectAppUrl));

    /// <summary>Check for update</summary>
    public string CheckForUpdate => Get("CHECK_FOR_UPDATE");

    /// <summary>Exp</summary>
    public string Expire => Get("EXPIRE");

    /// <summary>Default</summary>
    public string Default => Get("DEFAULT");

    /// <summary>Please wait</summary>
    public string PleaseWait => Get("PLEASE_WAIT");

    /// <summary>There is an error with your account. Please sign in again.</summary>
    public string AuthenticationError => Get("AUTHENTICATION_ERROR");

    /// <summary>/month</summary>
    public string PerMonth => Get("PER_MONTH");

    /// <summary>/6 months</summary>
    public string Per6Months => Get("PER_6_MONTHS");

    /// <summary>/year</summary>
    public string PerYear => Get("PER_YEAR");

    /// <summary>Global Servers</summary>
    public string GlobalServers => Get("GLOBAL_SERVERS");

    /// <summary>Remove Ads</summary>
    public string GlobalServersSubtitle => Get("GLOBAL_SERVERS_SUBTITLE");

    /// <summary>Sign in</summary>
    public string SignIn => Get("SIGN_IN");

    /// <summary>Sign in with Google</summary>
    public string SignInWithGoogle => Get("SIGN_IN_WITH_GOOGLE");

    /// <summary>Sign in with Apple</summary>
    public string SignInWithApple => Get("SIGN_IN_WITH_APPLE");

    /// <summary>Sign in with email</summary>
    public string SignInWithEmail => Get("SIGN_IN_WITH_EMAIL");

    /// <summary>Enter the email and password of your existing account. Signing in here does not create a new account.</summary>
    public string SignInWithEmailDesc => Get("SIGN_IN_WITH_EMAIL_DESC");

    /// <summary>For accounts created on our website.</summary>
    public string SignInEmailScopeHint => Get("SIGN_IN_EMAIL_SCOPE_HINT");

    /// <summary>Signed up with {provider}? Go back and use that option — those accounts have no password.</summary>
    public string SignInProviderHint(object provider) => Get("SIGN_IN_PROVIDER_HINT", ("provider", provider));

    /// <summary>Email</summary>
    public string Email => Get("EMAIL");

    /// <summary>Password</summary>
    public string Password => Get("PASSWORD");

    /// <summary>Forgot your password? Set or recover it on the account website.</summary>
    public string ForgotPassword => Get("FORGOT_PASSWORD");

    /// <summary>The email or password is wrong — or this account has never set a password. Set or recover it on the account website, ...</summary>
    public string SignInInvalidCredentials => Get("SIGN_IN_INVALID_CREDENTIALS");

    /// <summary>Too many sign-in attempts. Wait a few minutes, then try again.</summary>
    public string SignInCooldown => Get("SIGN_IN_COOLDOWN");

    /// <summary>Sign-in failed. Make sure this device is signed in to its app store account, then try again.</summary>
    public string SignInFailedMsg => Get("SIGN_IN_FAILED_MSG");

    /// <summary>No account was found for this email. Accounts are created on our website.</summary>
    public string SignInNoAccount => Get("SIGN_IN_NO_ACCOUNT");

    /// <summary>No account was found for this email. Accounts are created when you sign in with {provider}, or on our website.</summary>
    public string SignInNoAccountWithProvider(object provider) => Get("SIGN_IN_NO_ACCOUNT_WITH_PROVIDER", ("provider", provider));

    /// <summary>More than one account matches this login. Please contact support.</summary>
    public string SignInAccountAmbiguous => Get("SIGN_IN_ACCOUNT_AMBIGUOUS");

    /// <summary>Two-step verification</summary>
    public string TwoFactorTitle => Get("TWO_FACTOR_TITLE");

    /// <summary>This account is protected by two-step verification. Enter the code from your authenticator app.</summary>
    public string TwoFactorDesc => Get("TWO_FACTOR_DESC");

    /// <summary>Verification code</summary>
    public string TwoFactorCode => Get("TWO_FACTOR_CODE");

    /// <summary>Lost your authenticator? Enter your backup code instead.</summary>
    public string TwoFactorBackupHint => Get("TWO_FACTOR_BACKUP_HINT");

    /// <summary>The code is wrong. Check your authenticator app and try again.</summary>
    public string SignInWrongCode => Get("SIGN_IN_WRONG_CODE");

    /// <summary>That sign-in attempt has expired. Enter your password again.</summary>
    public string SignInChallengeExpired => Get("SIGN_IN_CHALLENGE_EXPIRED");

    /// <summary>This account uses a verification method this app version does not support. Update the app, or sign in on the account ...</summary>
    public string SignInUnsupportedTwoFactor => Get("SIGN_IN_UNSUPPORTED_TWO_FACTOR");

    /// <summary>Your new backup code</summary>
    public string NewBackupCodeTitle => Get("NEW_BACKUP_CODE_TITLE");

    /// <summary>You signed in with your backup code, so it has been replaced. Save the new one somewhere safe — it will never be show...</summary>
    public string NewBackupCodeDesc => Get("NEW_BACKUP_CODE_DESC");

    /// <summary>I saved it</summary>
    public string ISavedIt => Get("I_SAVED_IT");

    /// <summary>Back</summary>
    public string Back => Get("BACK");

    /// <summary>Confirm</summary>
    public string Confirm => Get("CONFIRM");

    /// <summary>Sign out</summary>
    public string SignOut => Get("SIGN_OUT");

    /// <summary>Please sign in to continue</summary>
    public string SignInToContinue => Get("SIGN_IN_TO_CONTINUE");

    /// <summary>Signed in as {email}</summary>
    public string SignedInAsX(object email) => Get("SIGNED_IN_AS_X", ("email", email));

    /// <summary>Already subscribed</summary>
    public string AlreadySubscribed => Get("ALREADY_SUBSCRIBED");

    /// <summary>Remove ads from global servers.</summary>
    public string GlobalServersNotice => Get("GLOBAL_SERVERS_NOTICE");

    /// <summary>Congratulations</summary>
    public string Congratulations => Get("CONGRATULATIONS");

    /// <summary>Your order has been processed and your subscription has been activated.</summary>
    public string PurchaseAndProcessIsCompleteMessage => Get("PURCHASE_AND_PROCESS_IS_COMPLETE_MESSAGE");

    /// <summary>You have been upgraded to a premium user.</summary>
    public string PremiumCodeProcessIsCompleteMessage => Get("PREMIUM_CODE_PROCESS_IS_COMPLETE_MESSAGE");

    /// <summary>Show servers</summary>
    public string ShowServers => Get("SHOW_SERVERS");

    /// <summary>Please wait to complete process...</summary>
    public string WaitingToCompleteOrderProcess => Get("WAITING_TO_COMPLETE_ORDER_PROCESS");

    /// <summary>You are premium</summary>
    public string YouArePremium => Get("YOU_ARE_PREMIUM");

    /// <summary>Your premium servers</summary>
    public string YourPremiumServers => Get("YOUR_PREMIUM_SERVERS");

    /// <summary>Manage subscription</summary>
    public string ManageSubscription => Get("MANAGE_SUBSCRIPTION");

    /// <summary>Your subscription is managed through the store where it was purchased.</summary>
    public string SubscriptionManagedWherePurchased => Get("SUBSCRIPTION_MANAGED_WHERE_PURCHASED");

    /// <summary>This device can't open your store's subscription settings. Manage your subscription from your phone, tablet or computer.</summary>
    public string SubscriptionManageOnAnotherDevice => Get("SUBSCRIPTION_MANAGE_ON_ANOTHER_DEVICE");

    /// <summary>Buy</summary>
    public string Buy => Get("BUY");

    /// <summary>Subscription</summary>
    public string Subscription => Get("SUBSCRIPTION");

    /// <summary>Sign out</summary>
    public string ConfirmSignOutTitle => Get("CONFIRM_SIGN_OUT_TITLE");

    /// <summary>Are you sure to sign out of your account?</summary>
    public string ConfirmSignOutDesc => Get("CONFIRM_SIGN_OUT_DESC");

    /// <summary>Delete my account</summary>
    public string DeleteMyAccount => Get("DELETE_MY_ACCOUNT");

    /// <summary>Permanently delete your account and personal data from our servers.</summary>
    public string DeleteMyAccountDesc => Get("DELETE_MY_ACCOUNT_DESC");

    /// <summary>This cannot be undone</summary>
    public string ConfirmDeleteAccountTitle => Get("CONFIRM_DELETE_ACCOUNT_TITLE");

    /// <summary>Your account and personal data will be permanently deleted, and every signed-in device is signed out and loses premium.</summary>
    public string ConfirmDeleteAccountDesc => Get("CONFIRM_DELETE_ACCOUNT_DESC");

    /// <summary>We cannot recover your premium codes after this, so save any you still need. Deleting does not cancel a code. One you...</summary>
    public string DeleteAccountCodesNote => Get("DELETE_ACCOUNT_CODES_NOTE");

    /// <summary>A subscription bought in this app is not cancelled by this — it stays with your store account and may keep renewing, ...</summary>
    public string DeleteAccountSubscriptionNote => Get("DELETE_ACCOUNT_SUBSCRIPTION_NOTE");

    /// <summary>Invoices are kept because tax law requires it, and are used for nothing else.</summary>
    public string DeleteAccountInvoicesNote => Get("DELETE_ACCOUNT_INVOICES_NOTE");

    /// <summary>I understand</summary>
    public string IUnderstand => Get("I_UNDERSTAND");

    /// <summary>Support ID</summary>
    public string SupportId => Get("SUPPORT_ID");

    /// <summary>Could not found VpnHood Global Servers profile.</summary>
    public string CouldNotFoundGlobalServersProfile => Get("COULD_NOT_FOUND_GLOBAL_SERVERS_PROFILE");

    /// <summary>Warning</summary>
    public string Warning => Get("WARNING");

    /// <summary>App language</summary>
    public string AppLanguage => Get("APP_LANGUAGE");

    /// <summary>Set your preferred language.</summary>
    public string AppLanguageDesc => Get("APP_LANGUAGE_DESC");

    /// <summary>Contribute edit languages</summary>
    public string ContributeEditLanguagesTitle => Get("CONTRIBUTE_EDIT_LANGUAGES_Title");

    /// <summary>If you notice a problem with the translation, we'd love your help in improving our translations. Just download the fi...</summary>
    public string ContributeEditLanguagesDesc => Get("CONTRIBUTE_EDIT_LANGUAGES_DESC");

    /// <summary>Your order could not be processed. If your order has been registered and activated by the store, please reach out to ...</summary>
    public string OrderProcessingFailed => Get("ORDER_PROCESSING_FAILED");

    /// <summary>Store message:</summary>
    public string StoreExceptionMessage => Get("STORE_EXCEPTION_MESSAGE");

    /// <summary>There is a problem reaching your store's billing service. Please check your connection and try again; if it keeps hap...</summary>
    public string BillingNetworkError => Get("BILLING_NETWORK_ERROR");

    /// <summary>In-app purchases are not available on this device or store account. This can happen with an outdated store app, an un...</summary>
    public string BillingUnavailable => Get("BILLING_UNAVAILABLE");

    /// <summary>We couldn't find a record of you owning this subscription or purchase. Please make sure you're signed in to the corre...</summary>
    public string BillingItemNotOwned => Get("BILLING_ITEM_NOT_OWNED");

    /// <summary>The selected plan is currently not available for purchase in your store. If you receive this message again, please co...</summary>
    public string BillingItemUnavailable => Get("BILLING_ITEM_UNAVAILABLE");

    /// <summary>Your order is currently being processed. Once your store confirms the payment, we'll activate it in the app. If you r...</summary>
    public string BillingPendingPurchase => Get("BILLING_PENDING_PURCHASE");

    /// <summary>Online purchase is not available.</summary>
    public string OnlinePurchaseIsNotAvailable => Get("ONLINE_PURCHASE_IS_NOT_AVAILABLE");

    /// <summary>Purchase Subscription</summary>
    public string PurchaseSubscription => Get("PURCHASE_SUBSCRIPTION");

    /// <summary>You currently have an active subscription.</summary>
    public string HaveActiveSubscription => Get("HAVE_ACTIVE_SUBSCRIPTION");

    /// <summary>The selected plan is already subscribed. You can choose another plan to change your current subscription.</summary>
    public string SelectedPlanAlreadySubscribed => Get("SELECTED_PLAN_ALREADY_SUBSCRIBED");

    /// <summary>To purchase a subscription, you need to sign in. If you wish, please proceed again.</summary>
    public string SignInCanceledByUser => Get("SIGN_IN_CANCELED_BY_USER");

    /// <summary>Cancel anytime in your store's subscription settings.</summary>
    public string CancelAnytimeInStore => Get("CANCEL_ANYTIME_IN_STORE");

    /// <summary>Always On</summary>
    public string AlwaysOn => Get("ALWAYS_ON");

    /// <summary>Always &lt;span class="text-promote-premium-color-premium"&gt;On&lt;/span&gt;</summary>
    public string AlwaysOnColored => Get("ALWAYS_ON_COLORED");

    /// <summary>Keeps device connected to the VPN at all times, even after restarts or network changes.</summary>
    public string AlwaysOnDesc => Get("ALWAYS_ON_DESC");

    /// <summary>Your VPN automatically reconnects if the connection drops to keep you protected.</summary>
    public string AlwaysOnPremiumDesc => Get("ALWAYS_ON_PREMIUM_DESC");

    /// <summary>Open the VPN settings on your device.</summary>
    public string AlwaysOnHowToTurnOnStep1 => Get("ALWAYS_ON_HOW_TO_TURN_ON_STEP_1");

    /// <summary>Find &lt;strong&gt;{appName}&lt;/strong&gt; and tap &lt;span class="text-label-large"&gt;{icon}&lt;/span&gt;</summary>
    public string AlwaysOnHowToTurnOnStep2(object appName, object icon) => Get("ALWAYS_ON_HOW_TO_TURN_ON_STEP_2", ("appName", appName), ("icon", icon));

    /// <summary>Enable &lt;strong&gt;Always-on VPN&lt;/strong&gt;</summary>
    public string AlwaysOnHowToTurnOnStep3 => Get("ALWAYS_ON_HOW_TO_TURN_ON_STEP_3");

    /// <summary>Kill Switch</summary>
    public string KillSwitch => Get("KILL_SWITCH");

    /// <summary>Kill &lt;span class="text-promote-premium-color-premium"&gt;Switch&lt;/span&gt;</summary>
    public string KillSwitchColored => Get("KILL_SWITCH_COLORED");

    /// <summary>Automatically blocks internet connection if the VPN disconnects.</summary>
    public string KillSwitchDesc => Get("KILL_SWITCH_DESC");

    /// <summary>Open the VPN settings on your device.</summary>
    public string KillSwitchHowToTurnOnStep1 => Get("KILL_SWITCH_HOW_TO_TURN_ON_STEP_1");

    /// <summary>Find &lt;strong&gt;{appName}&lt;/strong&gt; and tap &lt;span class="text-label-large"&gt;{icon}&lt;/span&gt;</summary>
    public string KillSwitchHowToTurnOnStep2(object appName, object icon) => Get("KILL_SWITCH_HOW_TO_TURN_ON_STEP_2", ("appName", appName), ("icon", icon));

    /// <summary>Enable &lt;strong&gt;Always-on VPN&lt;/strong&gt; and &lt;strong&gt;Block connections without VPN&lt;/strong&gt;</summary>
    public string KillSwitchHowToTurnOnStep3 => Get("KILL_SWITCH_HOW_TO_TURN_ON_STEP_3");

    /// <summary>Notifications</summary>
    public string Notifications => Get("NOTIFICATIONS");

    /// <summary>App &lt;span class="text-promote-premium-color-premium"&gt;Notifications&lt;/span&gt;</summary>
    public string AppNotificationsColored => Get("APP_NOTIFICATIONS_COLORED");

    /// <summary>Quickly monitor and control VPN from notification bar.</summary>
    public string NotificationsDesc => Get("NOTIFICATIONS_DESC");

    /// <summary>Turn on notification</summary>
    public string TurnOnNotification => Get("TURN_ON_NOTIFICATION");

    /// <summary>Turn off notification</summary>
    public string TurnOffNotification => Get("TURN_OFF_NOTIFICATION");

    /// <summary>Open the app’s notification settings.</summary>
    public string NotificationHowToTurnOnStep1 => Get("NOTIFICATION_HOW_TO_TURN_ON_STEP_1");

    /// <summary>Turn on &lt;strong&gt;"Allow notifications"&lt;/strong&gt;</summary>
    public string NotificationHowToTurnOnStep2 => Get("NOTIFICATION_HOW_TO_TURN_ON_STEP_2");

    /// <summary>Private DNS</summary>
    public string PrivateDns => Get("PRIVATE_DNS");

    /// <summary>Encrypts connection to website addresses. This prevents anyone from tracking which websites you visit.</summary>
    public string PrivateDnsDesc => Get("PRIVATE_DNS_DESC");

    /// <summary>Quick Launch</summary>
    public string QuickLaunch => Get("QUICK_LAUNCH");

    /// <summary>Quick &lt;span class="text-promote-premium-color-premium"&gt;Launch&lt;/span&gt;</summary>
    public string QuickLaunchColored => Get("QUICK_LAUNCH_COLORED");

    /// <summary>Connect to the VPN instantly from the notification bar with a single tap.</summary>
    public string QuickLaunchDesc => Get("QUICK_LAUNCH_DESC");

    /// <summary>Turn on quick launch</summary>
    public string QuickLaunchTurnOn => Get("QUICK_LAUNCH_TURN_ON");

    /// <summary>Unable to add Quick Launch. Try again later or add it manually.</summary>
    public string QuickLaunchTurnOnError => Get("QUICK_LAUNCH_TURN_ON_ERROR");

    /// <summary>Tap on the below button.</summary>
    public string QuickLaunchHowToTurnOnStep1 => Get("QUICK_LAUNCH_HOW_TO_TURN_ON_STEP_1");

    /// <summary>Tap on the &lt;strong&gt;Add&lt;/strong&gt; button.</summary>
    public string QuickLaunchHowToTurnOnStep2 => Get("QUICK_LAUNCH_HOW_TO_TURN_ON_STEP_2");

    /// <summary>Swipe down from the top of your screen to open the Quick Settings panel.</summary>
    public string QuickLaunchHowToTurnOnAlternativeStep1 => Get("QUICK_LAUNCH_HOW_TO_TURN_ON_ALTERNATIVE_STEP_1");

    /// <summary>Tap a &lt;strong&gt;+&lt;/strong&gt; or &lt;strong&gt;Add&lt;/strong&gt; button.</summary>
    public string QuickLaunchHowToTurnOnAlternativeStep2 => Get("QUICK_LAUNCH_HOW_TO_TURN_ON_ALTERNATIVE_STEP_2");

    /// <summary>In the &lt;strong&gt;Available buttons&lt;/strong&gt; find the &lt;strong&gt;{appName}&lt;/strong&gt;</summary>
    public string QuickLaunchHowToTurnOnAlternativeStep3(object appName) => Get("QUICK_LAUNCH_HOW_TO_TURN_ON_ALTERNATIVE_STEP_3", ("appName", appName));

    /// <summary>Touch and hold the icon, drag it to the section where the other active tiles are located.</summary>
    public string QuickLaunchHowToTurnOnAlternativeStep4 => Get("QUICK_LAUNCH_HOW_TO_TURN_ON_ALTERNATIVE_STEP_4");

    /// <summary>Tap &lt;strong&gt;Done&lt;/strong&gt; or the back button to save the changes.</summary>
    public string QuickLaunchHowToTurnOnAlternativeStep5 => Get("QUICK_LAUNCH_HOW_TO_TURN_ON_ALTERNATIVE_STEP_5");

    /// <summary>Proxies</summary>
    public string Proxies => Get("PROXIES");

    /// <summary>Manage how the app connects through proxies.</summary>
    public string ProxiesDesc => Get("PROXIES_DESC");

    /// <summary>Note: SOCKS &amp; HTTP Proxies have finger print and can be blocked easily by Firewalls.</summary>
    public string ProxyNote => Get("PROXY_NOTE");

    /// <summary>Proxy</summary>
    public string Proxy => Get("PROXY");

    /// <summary>Proxy mode</summary>
    public string ProxyMode => Get("PROXY_MODE");

    /// <summary>No Proxy</summary>
    public string NoProxy => Get("NO_PROXY");

    /// <summary>System</summary>
    public string System => Get("SYSTEM");

    /// <summary>Manual</summary>
    public string Manual => Get("MANUAL");

    /// <summary>No proxies added yet.</summary>
    public string ProxyListEmpty => Get("PROXY_LIST_EMPTY");

    /// <summary>No system proxy is configured on your device.</summary>
    public string NoSystemProxy => Get("NO_SYSTEM_PROXY");

    /// <summary>Authentication</summary>
    public string Authentication => Get("AUTHENTICATION");

    /// <summary>Reset states</summary>
    public string ProxyResetStates => Get("PROXY_RESET_STATES");

    /// <summary>No matches found for this filter.</summary>
    public string ProxyFilterNoResult => Get("PROXY_FILTER_NO_RESULT");

    /// <summary>The system is learning which proxy servers are most reliable. Performance may be slower at first.</summary>
    public string ProxyLearningMsg => Get("PROXY_LEARNING_MSG");

    /// <summary>Remove all</summary>
    public string RemoveAll => Get("REMOVE_ALL");

    /// <summary>Are you sure you want to remove all proxies?</summary>
    public string RemoveAllProxiesMsg => Get("REMOVE_ALL_PROXIES_MSG");

    /// <summary>Remove all failed</summary>
    public string RemoveAllFailed => Get("REMOVE_ALL_FAILED");

    /// <summary>Are you sure you want to remove all failed proxies?</summary>
    public string RemoveAllFailedMsg => Get("REMOVE_ALL_FAILED_MSG");

    /// <summary>Remove all disabled</summary>
    public string RemoveAllDisabled => Get("REMOVE_ALL_DISABLED");

    /// <summary>Are you sure you want to remove all disabled proxies?</summary>
    public string RemoveAllDisabledMsg => Get("REMOVE_ALL_DISABLED_MSG");

    /// <summary>Disable all failed</summary>
    public string DisableAllFailed => Get("DISABLE_ALL_FAILED");

    /// <summary>Are you sure you want to disable all failed proxies?</summary>
    public string DisableAllFailedProxiesMsg => Get("DISABLE_ALL_FAILED_PROXIES_MSG");

    /// <summary>Remove proxy</summary>
    public string RemoveProxy => Get("REMOVE_PROXY");

    /// <summary>Are you sure you want to remove the proxy?</summary>
    public string RemoveProxyMsg => Get("REMOVE_PROXY_MSG");

    /// <summary>Add proxy list</summary>
    public string AddProxyList => Get("ADD_PROXY_LIST");

    /// <summary>Add proxy</summary>
    public string AddProxy => Get("ADD_PROXY");

    /// <summary>Edit proxy</summary>
    public string EditProxy => Get("EDIT_PROXY");

    /// <summary>Import proxies</summary>
    public string ProxyImport => Get("PROXY_IMPORT");

    /// <summary>Import proxies</summary>
    public string ProxyImportTitle => Get("PROXY_IMPORT_TITLE");

    /// <summary>Paste the proxy entries you want to import. Each proxy should be on a new line.</summary>
    public string ProxyImportDesc => Get("PROXY_IMPORT_DESC");

    /// <summary>Proxy list</summary>
    public string ProxyImportLabel => Get("PROXY_IMPORT_LABEL");

    /// <summary>Import</summary>
    public string ProxyImportConfirm => Get("PROXY_IMPORT_CONFIRM");

    /// <summary>Host is required.</summary>
    public string ProxyRequiredHost => Get("PROXY_REQUIRED_HOST");

    /// <summary>Enter a valid port (1-65535).</summary>
    public string ProxyInvalidPort => Get("PROXY_INVALID_PORT");

    /// <summary>Protocol</summary>
    public string ProxyProtocol => Get("PROXY_PROTOCOL");

    /// <summary>Host</summary>
    public string ProxyHost => Get("PROXY_HOST");

    /// <summary>Port</summary>
    public string ProxyPort => Get("PROXY_PORT");

    /// <summary>Username</summary>
    public string ProxyUsername => Get("PROXY_USERNAME");

    /// <summary>Password</summary>
    public string ProxyPassword => Get("PROXY_PASSWORD");

    /// <summary>Enabled</summary>
    public string Enabled => Get("ENABLED");

    /// <summary>Info</summary>
    public string ProxyTabInfo => Get("PROXY_TAB_INFO");

    /// <summary>Status</summary>
    public string ProxyTabStatus => Get("PROXY_TAB_STATUS");

    /// <summary>Quality</summary>
    public string ProxyStatusQuality => Get("PROXY_STATUS_QUALITY");

    /// <summary>Penalty</summary>
    public string ProxyStatusPenalty => Get("PROXY_STATUS_PENALTY");

    /// <summary>Latency</summary>
    public string ProxyStatusLatency => Get("PROXY_STATUS_LATENCY");

    /// <summary>Last Succeeded</summary>
    public string ProxyStatusLastSucceeded => Get("PROXY_STATUS_LAST_SUCCEEDED");

    /// <summary>Last Failed</summary>
    public string ProxyStatusLastFailed => Get("PROXY_STATUS_LAST_FAILED");

    /// <summary>Error</summary>
    public string ProxyStatusError => Get("PROXY_STATUS_ERROR");

    /// <summary>Excellent</summary>
    public string Excellent => Get("EXCELLENT");

    /// <summary>Good</summary>
    public string Good => Get("GOOD");

    /// <summary>Fair</summary>
    public string Fair => Get("FAIR");

    /// <summary>Poor</summary>
    public string Poor => Get("POOR");

    /// <summary>Very Poor</summary>
    public string VeryPoor => Get("VERY_POOR");

    /// <summary>No data</summary>
    public string NoData => Get("NO_DATA");

    /// <summary>Succeeded</summary>
    public string Succeeded => Get("SUCCEEDED");

    /// <summary>Failed</summary>
    public string Failed => Get("FAILED");

    /// <summary>Disabled</summary>
    public string Disabled => Get("DISABLED");

    /// <summary>Auto-update URL</summary>
    public string ProxyAutoUpdateUrl => Get("PROXY_AUTO_UPDATE_URL");

    /// <summary>Add by URL</summary>
    public string AddByUrl => Get("ADD_BY_URL");

    /// <summary>URL</summary>
    public string Url => Get("URL");

    /// <summary>Enter proxy list URL</summary>
    public string ProxyAutoUpdateUrlPlaceholder => Get("PROXY_AUTO_UPDATE_URL_PLACEHOLDER");

    /// <summary>Auto-update</summary>
    public string AutoUpdate => Get("AUTO_UPDATE");

    /// <summary>Reload from URL</summary>
    public string ProxyReloadUrl => Get("PROXY_RELOAD_URL");

    /// <summary>Recent Connections</summary>
    public string RecentConnections => Get("RECENT_CONNECTIONS");

    /// <summary>minute</summary>
    public string Minute => Get("MINUTE");

    /// <summary>minutes</summary>
    public string Minutes => Get("MINUTES");

    /// <summary>hour</summary>
    public string Hour => Get("HOUR");

    /// <summary>hours</summary>
    public string Hours => Get("HOURS");

    /// <summary>second</summary>
    public string Second => Get("SECOND");

    /// <summary>seconds</summary>
    public string Seconds => Get("SECONDS");

    /// <summary>day</summary>
    public string Day => Get("DAY");

    /// <summary>days</summary>
    public string Days => Get("DAYS");

    /// <summary>{count} {unit} ago</summary>
    public string TimeSecondsAgo(object count, object unit) => Get("TIME_SECONDS_AGO", ("count", count), ("unit", unit));

    /// <summary>{count} {unit} ago</summary>
    public string TimeMinutesAgo(object count, object unit) => Get("TIME_MINUTES_AGO", ("count", count), ("unit", unit));

    /// <summary>{count} {unit} ago</summary>
    public string TimeHoursAgo(object count, object unit) => Get("TIME_HOURS_AGO", ("count", count), ("unit", unit));

    /// <summary>{count} {unit} ago</summary>
    public string TimeDaysAgo(object count, object unit) => Get("TIME_DAYS_AGO", ("count", count), ("unit", unit));

    /// <summary>just now</summary>
    public string TimeJustNow => Get("TIME_JUST_NOW");

    /// <summary>Filter IP</summary>
    public string FilterIp => Get("FILTER_IP");

    /// <summary>Support</summary>
    public string Support => Get("SUPPORT");

    /// <summary>24/7 Support</summary>
    public string _247Support => Get("24_7_SUPPORT");

    /// <summary>We're here for you 24/7. Get instant assistance from our dedicated support team.</summary>
    public string _247SupportDesc => Get("24_7_SUPPORT_DESC");

    /// <summary>Active</summary>
    public string Active => Get("ACTIVE");

    /// <summary>Auto Select</summary>
    public string AutoSelect => Get("AUTO_SELECT");

    /// <summary>Auto</summary>
    public string Auto => Get("AUTO");

    /// <summary>Custom</summary>
    public string Custom => Get("CUSTOM");

    /// <summary>Fastest</summary>
    public string Fastest => Get("FASTEST");

    /// <summary>Location</summary>
    public string Location => Get("LOCATION");

    /// <summary>Servers</summary>
    public string LocationTmp => Get("LOCATION_TMP");

    /// <summary>Locations</summary>
    public string Locations => Get("LOCATIONS");

    /// <summary>Servers</summary>
    public string LocationsTmp => Get("LOCATIONS_TMP");

    /// <summary>Loading Ad</summary>
    public string LoadingAd => Get("LOADING_AD");

    /// <summary>Leave it empty to display the default name.</summary>
    public string SaveEmptyToDisplayDefaultName => Get("SAVE_EMPTY_TO_DISPLAY_DEFAULT_NAME");

    /// <summary>Powered by</summary>
    public string PoweredBy => Get("POWERED_BY");

    /// <summary>VpnHood! ENGINE</summary>
    public string VpnhoodEngine => Get("VPNHOOD_ENGINE");

    /// <summary>All Future Apps</summary>
    public string AllFutureApps => Get("ALL_FUTURE_APPS");

    /// <summary>Select all</summary>
    public string SelectAll => Get("SELECT_ALL");

    /// <summary>Clear all</summary>
    public string ClearAll => Get("CLEAR_ALL");

    /// <summary>Select all items</summary>
    public string SelectAllItems => Get("SELECT_ALL_ITEMS");

    /// <summary>Clear all selected items</summary>
    public string ClearAllItems => Get("CLEAR_ALL_ITEMS");

    /// <summary>Are you sure?</summary>
    public string AreYouSure => Get("ARE_YOU_SURE");

    /// <summary>There is no reachable server from your region at this moment, Please try again later.</summary>
    public string UnreachableServerMessage => Get("UNREACHABLE_SERVER_MESSAGE");

    /// <summary>You connected to the VPN network, but There is no reachable server from your region at this moment, Please try again ...</summary>
    public string UnreachableServerLocationMessage => Get("UNREACHABLE_SERVER_LOCATION_MESSAGE");

    /// <summary>Oops! There are currently no reachable free servers in your region. You may try a premium connection for free to chec...</summary>
    public string UnreachableServerLocationMessageWithTryPremium => Get("UNREACHABLE_SERVER_LOCATION_MESSAGE_WITH_TRY_PREMIUM");

    /// <summary>You connected to the VPN network, but all servers in your selected location are unreachable from your region. Please ...</summary>
    public string UnreachableServerLocationMessageWithChangeToAuto => Get("UNREACHABLE_SERVER_LOCATION_MESSAGE_WITH_CHANGE_TO_AUTO");

    /// <summary>All proxies are currently unreachable.</summary>
    public string UnreachableProxiesMessage => Get("UNREACHABLE_PROXIES_MESSAGE");

    /// <summary>{start} - {end} of {total}</summary>
    public string PaginationStatus(object start, object end, object total) => Get("PAGINATION_STATUS", ("start", start), ("end", end), ("total", total));

    /// <summary>Change and reconnect</summary>
    public string ChangeToAutoAndReconnect => Get("CHANGE_TO_AUTO_AND_RECONNECT");

    /// <summary>Free Locations</summary>
    public string FreeLocations => Get("FREE_LOCATIONS");

    /// <summary>Premium Locations</summary>
    public string PremiumLocations => Get("PREMIUM_LOCATIONS");

    /// <summary>Selected Location is &lt;span class="text-uppercase text-promote-premium-color-premium"&gt;Premium&lt;/span&gt;</summary>
    public string SelectedLocationIsPremium => Get("SELECTED_LOCATION_IS_PREMIUM");

    /// <summary>Selected Location is&lt;br/&gt; &lt;span class="text-uppercase text-promote-premium-color-free"&gt;FREE&lt;/span&gt; but has &lt;span clas...</summary>
    public string SelectedLocationIsFree => Get("SELECTED_LOCATION_IS_FREE");

    /// <summary>Go Back</summary>
    public string GoBack => Get("GO_BACK");

    /// <summary>Free Server</summary>
    public string SelectedFreeServer => Get("SELECTED_FREE_SERVER");

    /// <summary>Unlimited access</summary>
    public string SelectedFreeServerDesc => Get("SELECTED_FREE_SERVER_DESC");

    /// <summary>Free access for {minutes} minutes.</summary>
    public string SelectedFreeServerUnlimitedDesc(object minutes) => Get("SELECTED_FREE_SERVER_UNLIMITED_DESC", ("minutes", minutes));

    /// <summary>Free Server by Ad</summary>
    public string SelectedFreeServerByRewardedAd => Get("SELECTED_FREE_SERVER_BY_REWARDED_AD");

    /// <summary>Watch an ad for {minutes} minutes of free.</summary>
    public string SelectedFreeServerByRewardedAdDesc(object minutes) => Get("SELECTED_FREE_SERVER_BY_REWARDED_AD_DESC", ("minutes", minutes));

    /// <summary>Unlimited access.</summary>
    public string SelectedFreeServerByRewardedAdUnlimitedDesc => Get("SELECTED_FREE_SERVER_BY_REWARDED_AD_UNLIMITED_DESC");

    /// <summary>Watch Ad</summary>
    public string WatchRewardedAd => Get("WATCH_REWARDED_AD");

    /// <summary>Premium for {minutes} minutes.</summary>
    public string WatchRewardedAdDesc(object minutes) => Get("WATCH_REWARDED_AD_DESC", ("minutes", minutes));

    /// <summary>Try Premium</summary>
    public string TryPremium => Get("TRY_PREMIUM");

    /// <summary>Try Premium for Free</summary>
    public string TryPremiumForFree => Get("TRY_PREMIUM_FOR_FREE");

    /// <summary>Premium for {minutes} minutes.</summary>
    public string TryPremiumDesc(object minutes) => Get("TRY_PREMIUM_DESC", ("minutes", minutes));

    /// <summary>Premium by code</summary>
    public string PremiumByCode => Get("PREMIUM_BY_CODE");

    /// <summary>Unlock more features.</summary>
    public string GoPremiumDesc => Get("GO_PREMIUM_DESC");

    /// <summary>Upgrade</summary>
    public string Upgrade => Get("UPGRADE");

    /// <summary>Unknown Error</summary>
    public string UnknownError => Get("UNKNOWN_ERROR");

    /// <summary>You are already connected to the selected location.</summary>
    public string AlreadyConnectedToLocation => Get("ALREADY_CONNECTED_TO_LOCATION");

    /// <summary>Could not find the client profile ID of the selected location. If you receive this message again, please let us know.</summary>
    public string ClientProfileIdNotFoundMessage => Get("CLIENT_PROFILE_ID_NOT_FOUND_MESSAGE");

    /// <summary>or</summary>
    public string Or => Get("OR");

    /// <summary>Could not connect to the server. If you receive this message again, please let us know.</summary>
    public string CouldNotConnectToServer => Get("COULD_NOT_CONNECT_TO_SERVER");

    /// <summary>Ultra Fast Speed</summary>
    public string UltraFastSpeed => Get("ULTRA_FAST_SPEED");

    /// <summary>Access to faster and less crowded servers for a better VPN experience.</summary>
    public string UltraFastSpeedDesc => Get("ULTRA_FAST_SPEED_DESC");

    /// <summary>Remove Ads</summary>
    public string RemoveAd => Get("REMOVE_AD");

    /// <summary>completely ad-free experience without delay and interruption.</summary>
    public string RemoveAdDesc => Get("REMOVE_AD_DESC");

    /// <summary>More Locations</summary>
    public string MoreLocations => Get("MORE_LOCATIONS");

    /// <summary>Unlock a world of content through access to premium servers in more countries.</summary>
    public string MoreLocationsDesc => Get("MORE_LOCATIONS_DESC");

    /// <summary>Purchase</summary>
    public string Purchase => Get("PURCHASE");

    /// <summary>Restore purchase</summary>
    public string RestorePurchase => Get("RESTORE_PURCHASE");

    /// <summary>Already premium? Sign in</summary>
    public string AlreadyPremium => Get("ALREADY_PREMIUM");

    /// <summary>We could not find a subscription to restore. If you subscribed with a different store account, switch to it and try a...</summary>
    public string NoPurchaseToRestore => Get("NO_PURCHASE_TO_RESTORE");

    /// <summary>We found your previous purchase, but it is no longer active. To become premium again, start a new subscription.</summary>
    public string RestoredPurchaseExpiredMsg => Get("RESTORED_PURCHASE_EXPIRED_MSG");

    /// <summary>1 Month</summary>
    public string _1Month => Get("1_MONTH");

    /// <summary>6 Months</summary>
    public string _6Months => Get("6_MONTHS");

    /// <summary>1 Year</summary>
    public string _1Year => Get("1_YEAR");

    /// <summary>Auto renew at</summary>
    public string AutoRenewAt => Get("AUTO_RENEW_AT");

    /// <summary>Extend it</summary>
    public string ExtendIt => Get("EXTEND_IT");

    /// <summary>Account</summary>
    public string Account => Get("ACCOUNT");

    /// <summary>Extend &lt;span class="text-uppercase text-promote-premium-color-premium"&gt;Premium&lt;/span&gt; Session</summary>
    public string ExtendPremiumSession => Get("EXTEND_PREMIUM_SESSION");

    /// <summary>Show Ad</summary>
    public string ShowAd => Get("SHOW_AD");

    /// <summary>Add {minutes} minutes to current session after watch ad.</summary>
    public string ExtendByRewardedAdDesc(object minutes) => Get("EXTEND_BY_REWARDED_AD_DESC", ("minutes", minutes));

    /// <summary>Subscribed since</summary>
    public string SubscribedSince => Get("SUBSCRIBED_SINCE");

    /// <summary>Next payment</summary>
    public string NextPayment => Get("NEXT_PAYMENT");

    /// <summary>Auto Renew</summary>
    public string AutoRenew => Get("AUTO_RENEW");

    /// <summary>Expiration Time</summary>
    public string ExpirationTime => Get("EXPIRATION_TIME");

    /// <summary>Price</summary>
    public string Price => Get("PRICE");

    /// <summary>Upgrade your account to &lt;span class="text-active"&gt;PREMIUM&lt;/span&gt; and get more features.</summary>
    public string UpgradeAccountDesc => Get("UPGRADE_ACCOUNT_DESC");

    /// <summary>Could not find any available server in the selected location.</summary>
    public string CouldNotFindAvailableServerInSelectedLocation => Get("COULD_NOT_FIND_AVAILABLE_SERVER_IN_SELECTED_LOCATION");

    /// <summary>There are no additional locations available for selection.</summary>
    public string NoAdditionalLocationAvailable => Get("NO_ADDITIONAL_LOCATION_AVAILABLE");

    /// <summary>Ooops! Nothing is available. Contact support if you receive this message again.</summary>
    public string NoClientProfileAvailable => Get("NO_CLIENT_PROFILE_AVAILABLE");

    /// <summary>Please stay in the app until the ad finishes. If you leave the app, your session will not be extended.</summary>
    public string ExtendByRewardedAdNote => Get("EXTEND_BY_REWARDED_AD_NOTE");

    /// <summary>Congratulations! Your session has been successfully extended.</summary>
    public string ExtendByRewardedAdConfirmMsg => Get("EXTEND_BY_REWARDED_AD_CONFIRM_MSG");

    /// <summary>Note</summary>
    public string Note => Get("NOTE");

    /// <summary>Search</summary>
    public string Search => Get("SEARCH");

    /// <summary>I have a Premium Code</summary>
    public string IHaveAPremiumCode => Get("I_HAVE_A_PREMIUM_CODE");

    /// <summary>Enter premium code</summary>
    public string EnterPremiumCode => Get("ENTER_PREMIUM_CODE");

    /// <summary>If your code has an expiration date, it will become active from the moment you enter it.</summary>
    public string ActivePremiumKeyExpirationNotice => Get("ACTIVE_PREMIUM_KEY_EXPIRATION_NOTICE");

    /// <summary>Your code has been activated, and you are now a premium user.</summary>
    public string PremiumCodeSuccessfullyAddedMessage => Get("PREMIUM_CODE_SUCCESSFULLY_ADDED_MESSAGE");

    /// <summary>Important</summary>
    public string Important => Get("IMPORTANT");

    /// <summary>Enter your code</summary>
    public string EnterYourCode => Get("ENTER_YOUR_CODE");

    /// <summary>Activate</summary>
    public string Activate => Get("ACTIVATE");

    /// <summary>Single IP:</summary>
    public string SingleIp => Get("SINGLE_IP");

    /// <summary>Range of IP:</summary>
    public string RangesOfIp => Get("RANGES_OF_IP");

    /// <summary>CIDR Notation:</summary>
    public string CidrNotation => Get("CIDR_NOTATION");

    /// <summary># YOUR COMMENT 2.2.2.2</summary>
    public string SplitIpPlaceHolder => Get("SPLIT_IP_PLACE_HOLDER");

    /// <summary>Split IPs Via Device</summary>
    public string SplitIpsViaDevice => Get("SPLIT_IPS_VIA_DEVICE");

    /// <summary>Include or exclude specific IP addresses at the device level.</summary>
    public string SplitIpsViaDeviceDesc => Get("SPLIT_IPS_VIA_DEVICE_DESC");

    /// <summary>Choose which IP addresses use the VPN on your device.</summary>
    public string SplitIpsViaDeviceShortDesc => Get("SPLIT_IPS_VIA_DEVICE_SHORT_DESC");

    /// <summary>Split IPs Via App</summary>
    public string SplitIpsViaApp => Get("SPLIT_IPS_VIA_APP");

    /// <summary>Include, exclude, or block specific IP addresses at the app level.</summary>
    public string SplitIpsViaAppDesc => Get("SPLIT_IPS_VIA_APP_DESC");

    /// <summary>Choose which IP addresses use the VPN, bypass it, or are blocked in the app.</summary>
    public string SplitIpsViaAppShortDesc => Get("SPLIT_IPS_VIA_APP_SHORT_DESC");

    /// <summary>Split DNS</summary>
    public string SplitDns => Get("SPLIT_DNS");

    /// <summary>Decide whether DNS queries follow your split rules or always stay in the VPN.</summary>
    public string SplitDnsShortDesc => Get("SPLIT_DNS_SHORT_DESC");

    /// <summary>DNS queries reveal every website you visit. When they travel outside the VPN, your network provider can see and even ...</summary>
    public string SplitDnsDesc => Get("SPLIT_DNS_DESC");

    /// <summary>This option lets DNS queries travel outside the VPN, where your network can see them.</summary>
    public string SplitDnsLeakWarning => Get("SPLIT_DNS_LEAK_WARNING");

    /// <summary>Always use VPN</summary>
    public string SplitDnsIncludeAll => Get("SPLIT_DNS_INCLUDE_ALL");

    /// <summary>All DNS queries go through the VPN, even when a split tunneling rule excludes them. A query the server cannot deliver...</summary>
    public string SplitDnsIncludeAllDesc => Get("SPLIT_DNS_INCLUDE_ALL_DESC");

    /// <summary>Allow Bypass VPN</summary>
    public string SplitDnsDefaultRoute => Get("SPLIT_DNS_DEFAULT_ROUTE");

    /// <summary>DNS queries follow your split tunneling rules like any other traffic.</summary>
    public string SplitDnsDefaultRouteDesc => Get("SPLIT_DNS_DEFAULT_ROUTE_DESC");

    /// <summary>Allow Split Tunneling</summary>
    public string SplitTunnelingToggle => Get("SPLIT_TUNNELING_TOGGLE");

    /// <summary>Selected apps and destinations connect directly for better speed and experience, but your IP address can be exposed t...</summary>
    public string SplitTunnelingToggleDesc => Get("SPLIT_TUNNELING_TOGGLE_DESC");

    /// <summary>All traffic stays inside the VPN. Destinations the server cannot carry are blocked instead of connecting directly, so...</summary>
    public string SplitTunnelingDisabledDesc => Get("SPLIT_TUNNELING_DISABLED_DESC");

    /// <summary>Split tunneling is off, so this setting has no effect.</summary>
    public string SplitTunnelingDisabledAlert => Get("SPLIT_TUNNELING_DISABLED_ALERT");

    /// <summary>Turn On</summary>
    public string TurnOn => Get("TURN_ON");

    /// <summary>IP Leak Risk</summary>
    public string LeakIp => Get("LEAK_IP");

    /// <summary>This server does not carry every destination; unsupported ones connect directly while splitting is allowed.</summary>
    public string ServerSplitTrafficNotice => Get("SERVER_SPLIT_TRAFFIC_NOTICE");

    /// <summary>Split IPv6</summary>
    public string SplitIpv6 => Get("SPLIT_IPV6");

    /// <summary>Choose what happens to IPv6 when the server has no public IPv6 address.</summary>
    public string SplitIpv6ShortDesc => Get("SPLIT_IPV6_SHORT_DESC");

    /// <summary>Some VPN servers have no public IPv6 address and cannot carry IPv6 traffic. Choose what happens to IPv6 while you are...</summary>
    public string SplitIpv6Desc => Get("SPLIT_IPV6_DESC");

    /// <summary>Protect</summary>
    public string SplitIpv6Block => Get("SPLIT_IPV6_BLOCK");

    /// <summary>When the server has no public IPv6 address, IPv6 traffic is dropped. Nothing travels outside the VPN, but IPv6-only d...</summary>
    public string SplitIpv6BlockDesc => Get("SPLIT_IPV6_BLOCK_DESC");

    /// <summary>Bypass VPN</summary>
    public string SplitIpv6Exclude => Get("SPLIT_IPV6_EXCLUDE");

    /// <summary>When the server has no public IPv6 address, IPv6 traffic connects directly, outside the VPN. Everything keeps working...</summary>
    public string SplitIpv6ExcludeDesc => Get("SPLIT_IPV6_EXCLUDE_DESC");

    /// <summary>This option lets IPv6 travel outside the VPN when the server has no public IPv6 address, exposing your IPv6 address.</summary>
    public string SplitIpv6LeakWarning => Get("SPLIT_IPV6_LEAK_WARNING");

    /// <summary>Exclude IPs</summary>
    public string ExcludeIps => Get("EXCLUDE_IPS");

    /// <summary>Include IPs</summary>
    public string IncludeIps => Get("INCLUDE_IPS");

    /// <summary>Block IPs</summary>
    public string BlockIps => Get("BLOCK_IPS");

    /// <summary>IP Addresses</summary>
    public string IpAddresses => Get("IP_ADDRESSES");

    /// <summary>Split IP addresses</summary>
    public string SplitIpAddresses => Get("SPLIT_IP_ADDRESSES");

    /// <summary>&lt;span class="text-promote-premium-color-premium"&gt;Split IP&lt;/span&gt; addresses</summary>
    public string SplitIpAddressesColored => Get("SPLIT_IP_ADDRESSES_COLORED");

    /// <summary>Include or exclude specific host IP addresses from VPN traffic.</summary>
    public string SplitIpAddressesDesc => Get("SPLIT_IP_ADDRESSES_DESC");

    /// <summary>Smartly route traffic by defining IP ranges for privacy and flexibility.</summary>
    public string SplitIpAddressesPremiumDesc => Get("SPLIT_IP_ADDRESSES_PREMIUM_DESC");

    /// <summary>Manage IP addresses</summary>
    public string ManageIpAddresses => Get("MANAGE_IP_ADDRESSES");

    /// <summary>Comment:</summary>
    public string Comment => Get("COMMENT");

    /// <summary>start text with #</summary>
    public string CommentDesc => Get("COMMENT_DESC");

    /// <summary>Exclude Domains</summary>
    public string ExcludeDomains => Get("EXCLUDE_DOMAINS");

    /// <summary>Include Domains</summary>
    public string IncludeDomains => Get("INCLUDE_DOMAINS");

    /// <summary>Block Domains</summary>
    public string BlockDomains => Get("BLOCK_DOMAINS");

    /// <summary># YOUR COMMENT example.com</summary>
    public string SplitDomainPlaceHolder => Get("SPLIT_DOMAIN_PLACE_HOLDER");

    /// <summary>Exact domain:</summary>
    public string ExactDomain => Get("EXACT_DOMAIN");

    /// <summary>Wildcard (all subdomains):</summary>
    public string WildcardDomain => Get("WILDCARD_DOMAIN");

    /// <summary>Rules: case-insensitive, one domain per line. Block &gt; Exclude &gt; Include.</summary>
    public string DomainRulesHint => Get("DOMAIN_RULES_HINT");

    /// <summary>Increasing the number of IPs in this section may be limited by your operating system, potentially preventing the VPN ...</summary>
    public string CautionIncreaseNumberOfIp => Get("CAUTION_INCREASE_NUMBER_OF_IP");

    /// <summary>Revert</summary>
    public string Revert => Get("REVERT");

    /// <summary>More info</summary>
    public string MoreInfo => Get("MORE_INFO");

    /// <summary>Alert</summary>
    public string Alert => Get("ALERT");

    /// <summary>Info</summary>
    public string Info => Get("INFO");

    /// <summary>Message</summary>
    public string Message => Get("MESSAGE");

    /// <summary>Statistics</summary>
    public string Statistics => Get("STATISTICS");

    /// <summary>If you'd like to use the "Premium Code", please first log out of your account. If your current subscription is still ...</summary>
    public string SignOutToUsePremiumCodeMsg => Get("SIGN_OUT_TO_USE_PREMIUM_CODE_MSG");

    /// <summary>Remove code</summary>
    public string ConfirmRemovePremiumCode => Get("CONFIRM_REMOVE_PREMIUM_CODE");

    /// <summary>Are you sure you want to remove the premium code?</summary>
    public string ConfirmRemovePremiumCodeDesc => Get("CONFIRM_REMOVE_PREMIUM_CODE_DESC");

    /// <summary>Remove code</summary>
    public string RemoveCode => Get("REMOVE_CODE");

    /// <summary>Change premium code</summary>
    public string ChangePremiumCode => Get("CHANGE_PREMIUM_CODE");

    /// <summary>Replace the current code with a new one in a single step. The new code takes over immediately; the old one stays vali...</summary>
    public string ChangePremiumCodeDesc => Get("CHANGE_PREMIUM_CODE_DESC");

    /// <summary>Change code</summary>
    public string ChangeCode => Get("CHANGE_CODE");

    /// <summary>Premium user</summary>
    public string PremiumUser => Get("PREMIUM_USER");

    /// <summary>The code has already been used in other devices.</summary>
    public string AlertForUsedPremiumCodeMoreThanOneDevice => Get("ALERT_FOR_USED_PREMIUM_CODE_MORE_THAN_ONE_DEVICE");

    /// <summary>Subscription details</summary>
    public string SubscriptionDetails => Get("SUBSCRIPTION_DETAILS");

    /// <summary>Would you like to change?</summary>
    public string WouldYouLikeToChange => Get("WOULD_YOU_LIKE_TO_CHANGE");

    /// <summary>Active user</summary>
    public string ActiveUser => Get("ACTIVE_USER");

    /// <summary>Activated on</summary>
    public string ActivatedOn => Get("ACTIVATED_ON");

    /// <summary>Used device</summary>
    public string UsedDevice => Get("USED_DEVICE");

    /// <summary>Device</summary>
    public string Device => Get("DEVICE");

    /// <summary>More than {x} devices</summary>
    public string MoreThanXDevices(object x) => Get("MORE_THAN_X_DEVICES", ("x", x));

    /// <summary>Date</summary>
    public string Date => Get("DATE");

    /// <summary>Premium info</summary>
    public string PremiumInfo => Get("PREMIUM_INFO");

    /// <summary>Premium by</summary>
    public string PremiumBy => Get("PREMIUM_BY");

    /// <summary>Premium code</summary>
    public string PremiumCode => Get("PREMIUM_CODE");

    /// <summary>Your code is saved. Your subscription is used first, and this code will be used when it ends.</summary>
    public string PremiumCodeSavedForLaterMsg => Get("PREMIUM_CODE_SAVED_FOR_LATER_MSG");

    /// <summary>You can use this code o {x} devices</summary>
    public string PremiumCodeDesc(object x) => Get("PREMIUM_CODE_DESC", ("x", x));

    /// <summary>Expiration date</summary>
    public string ExpirationDate => Get("EXPIRATION_DATE");

    /// <summary>Never</summary>
    public string Never => Get("NEVER");

    /// <summary>Last used</summary>
    public string LastUsed => Get("LAST_USED");

    /// <summary>Server and IP</summary>
    public string ServerAndIp => Get("SERVER_AND_IP");

    /// <summary>Your protected IP</summary>
    public string YourProtectedIp => Get("YOUR_PROTECTED_IP");

    /// <summary>Country</summary>
    public string Country => Get("COUNTRY");

    /// <summary>Region</summary>
    public string Region => Get("REGION");

    /// <summary>UDP supported</summary>
    public string UdpSupported => Get("UDP_SUPPORTED");

    /// <summary>Display info after connection</summary>
    public string DisplayInfoAfterConnection => Get("DISPLAY_INFO_AFTER_CONNECTION");

    /// <summary>Devices</summary>
    public string Devices => Get("DEVICES");

    /// <summary>Max device</summary>
    public string MaxDevice => Get("MAX_DEVICE");

    /// <summary>Session traffic</summary>
    public string SessionTraffic => Get("SESSION_TRAFFIC");

    /// <summary>Used</summary>
    public string Used => Get("USED");

    /// <summary>Max traffic</summary>
    public string MaxTraffic => Get("MAX_TRAFFIC");

    /// <summary>Unlimited</summary>
    public string Unlimited => Get("UNLIMITED");

    /// <summary>Monthly traffic</summary>
    public string MonthlyTraffic => Get("MONTHLY_TRAFFIC");

    /// <summary>Total traffic</summary>
    public string TotalTraffic => Get("TOTAL_TRAFFIC");

    /// <summary>Activation and expiration date and last use.</summary>
    public string StatisticsDateCardDesc => Get("STATISTICS_DATE_CARD_DESC");

    /// <summary>Current connection server.</summary>
    public string StatisticsServerCardDesc => Get("STATISTICS_SERVER_CARD_DESC");

    /// <summary>In the last {x} days.</summary>
    public string StatisticsDevicesCardDesc(object x) => Get("STATISTICS_DEVICES_CARD_DESC", ("x", x));

    /// <summary>Maximum allowed and used traffic for the current connection.</summary>
    public string StatisticsSessionTrafficCardDesc => Get("STATISTICS_SESSION_TRAFFIC_CARD_DESC");

    /// <summary>Maximum allowed and used traffic per month.</summary>
    public string StatisticsMonthlyTrafficCardDesc => Get("STATISTICS_MONTHLY_TRAFFIC_CARD_DESC");

    /// <summary>Maximum allowed and used traffic since initial use.</summary>
    public string StatisticsTotalTrafficCardDesc => Get("STATISTICS_TOTAL_TRAFFIC_CARD_DESC");

    /// <summary>Only numbers are allowed.</summary>
    public string PremiumCodeNumberRuleMsg => Get("PREMIUM_CODE_NUMBER_RULE_MSG");

    /// <summary>The code must be 20 characters.</summary>
    public string PremiumCodeCountRuleMsg => Get("PREMIUM_CODE_COUNT_RULE_MSG");

    /// <summary>Your premium access has expired.</summary>
    public string PremiumAccessExpiredMsg => Get("PREMIUM_ACCESS_EXPIRED_MSG");

    /// <summary>Yes switch now</summary>
    public string YesSwitchNow => Get("YES_SWITCH_NOW");

    /// <summary>Your server key has expired.</summary>
    public string ServerKeyExpired => Get("SERVER_KEY_EXPIRED");

    /// <summary>The premium code is not valid. If you believe this is an error, please contact support.</summary>
    public string InvalidAccessCode => Get("INVALID_ACCESS_CODE");

    /// <summary>Your subscription is active, but this device could not be given access. Please try again in a moment — if it keeps ha...</summary>
    public string SubscriptionNotProvisionedMsg => Get("SUBSCRIPTION_NOT_PROVISIONED_MSG");

    /// <summary>Premium code details</summary>
    public string PremiumCodeDetails => Get("PREMIUM_CODE_DETAILS");

    /// <summary>More details</summary>
    public string MoreDetails => Get("MORE_DETAILS");

    /// <summary>Premium code is active</summary>
    public string PremiumCodeIsActive => Get("PREMIUM_CODE_IS_ACTIVE");

    /// <summary>Could not establish connection in given time. Please try again.</summary>
    public string ConnectionTimeoutMsg => Get("CONNECTION_TIMEOUT_MSG");

    /// <summary>Your premium connection time has expired.</summary>
    public string PremiumConnectionExpiredMsg => Get("PREMIUM_CONNECTION_EXPIRED_MSG");

    /// <summary>Your daily usage limit for the selected option has been reached. Please use the other available options.</summary>
    public string DailyLimitExceededMsg => Get("DAILY_LIMIT_EXCEEDED_MSG");

    /// <summary>Purchase via Web</summary>
    public string PurchaseViaWeb => Get("PURCHASE_VIA_WEB");

    /// <summary>The app was closed before the connection could complete. The free version doesn't support establishing a connection i...</summary>
    public string ShowAdNoUiMsg => Get("SHOW_AD_NO_UI_MSG");

    /// <summary>Your internet connection appears to be offline or too slow. Please check your connection and try again in a few moments.</summary>
    public string NoInternetMsg => Get("NO_INTERNET_MSG");

    /// <summary>VPN service encountered an issue. Please try again.</summary>
    public string VpnServiceUnreachableMsg => Get("VPN_SERVICE_UNREACHABLE_MSG");

    /// <summary>Diagnoser has finished and no issue has been detected</summary>
    public string DiagnoseFinishedNoErrorMsg => Get("DIAGNOSE_FINISHED_NO_ERROR_MSG");

    /// <summary>An error occurred during premium code activation. Please try again. If the issue persists, contact us.</summary>
    public string ProfileIdNotFoundDuringValidationMsg => Get("PROFILE_ID_NOT_FOUND_DURING_VALIDATION_MSG");

    /// <summary>The connection method you selected (Free, Watch Ad, or Try Premium) was refused. No worries, just pick a different ty...</summary>
    public string PlanRejectedMsg => Get("PLAN_REJECTED_MSG");

    /// <summary>Our servers are in maintenance mode at the moment. We're working to get things back up and running, so please try aga...</summary>
    public string MaintenanceModeMsg => Get("MAINTENANCE_MODE_MSG");

    /// <summary>No servers are available in the selected location. Please try again later or choose another location.</summary>
    public string NoServerAvailableMsg => Get("NO_SERVER_AVAILABLE_MSG");

    /// <summary>Your selected server is now a premium server and will be automatically updated in your list. Please select a differen...</summary>
    public string PremiumLocationMsg => Get("PREMIUM_LOCATION_MSG");

    /// <summary>It seems there was an issue and the reward for watching that ad wasn't registered. We're sorry for the inconvenience!...</summary>
    public string RewardNotEarnedMsg => Get("REWARD_NOT_EARNED_MSG");

    /// <summary>The VPN service didn't start in time. Please try again.</summary>
    public string VpnServiceTimeoutMsg => Get("VPN_SERVICE_TIMEOUT_MSG");

    /// <summary>No ads is currently available. Please try again in a few minutes.</summary>
    public string RewardedAdLoadErrorMsg => Get("REWARDED_AD_LOAD_ERROR_MSG");

    /// <summary>There was an issue playing the ad. Please try again in a moment.</summary>
    public string RewardedAdShowErrorMsg => Get("REWARDED_AD_SHOW_ERROR_MSG");

    /// <summary>You're connected to the VPN, but your connection isn't stable. This might resolve in a few minutes. If not, please se...</summary>
    public string NoStableVpnMsg => Get("NO_STABLE_VPN_MSG");

    /// <summary>The VPN service isn't ready. Please try again. If the issue persists, let us know.</summary>
    public string VpnServiceNotReadyMsg => Get("VPN_SERVICE_NOT_READY_MSG");

    /// <summary>The code entered is invalid. Please check the numbers and try again.</summary>
    public string InvalidPremiumCodeNumbersMsg => Get("INVALID_PREMIUM_CODE_NUMBERS_MSG");

    /// <summary>Could not connect to the server. Please try again. If the issue persists, let us know.</summary>
    public string LoginConnectionErrorMsg => Get("LOGIN_CONNECTION_ERROR_MSG");

    /// <summary>Custom server address</summary>
    public string CustomEndpoint => Get("CUSTOM_ENDPOINT");

    /// <summary>Use custom server address</summary>
    public string CustomEndpointEnable => Get("CUSTOM_ENDPOINT_ENABLE");

    /// <summary>Server IP and port</summary>
    public string CustomEndpointPlaceHolder => Get("CUSTOM_ENDPOINT_PLACE_HOLDER");

    /// <summary>Enter an server IP and port in the following format:</summary>
    public string CustomEndpointDesc => Get("CUSTOM_ENDPOINT_DESC");

    /// <summary>Please enter a valid IP address (IPv4 or IPv6).</summary>
    public string CustomEndpointValidationError => Get("CUSTOM_ENDPOINT_VALIDATION_ERROR");

    /// <summary>Quick Launch is a premium feature. Upgrade to unlock it!</summary>
    public string QuickLaunchNotSupportedMsg => Get("QUICK_LAUNCH_NOT_SUPPORTED_MSG");

    /// <summary>Always on is a premium feature. Upgrade to unlock it!</summary>
    public string AlwaysOnNotSupportedMsg => Get("ALWAYS_ON_NOT_SUPPORTED_MSG");

    /// <summary>Kill switch is a premium feature. Upgrade to unlock it!</summary>
    public string KillSwitchNotSupportedMsg => Get("KILL_SWITCH_NOT_SUPPORTED_MSG");

    /// <summary>You have unsaved changes. Do you want to leave without saving?</summary>
    public string UnsavedChangesMessage => Get("UNSAVED_CHANGES_MESSAGE");

    /// <summary>There seems to be an issue with your Google account. Please ensure that you are logged into a valid Google account an...</summary>
    public string GooglePlayLoginNoCredentialError => Get("GOOGLE_PLAY_LOGIN_NO_CREDENTIAL_ERROR");

    /// <summary>Feedback</summary>
    public string Feedback => Get("FEEDBACK");

    /// <summary>Your feedback motivates us to keep making VpnHood better. How would you rate your experience?</summary>
    public string FeedbackDesc => Get("FEEDBACK_DESC");

    /// <summary>Submit</summary>
    public string Submit => Get("SUBMIT");

    /// <summary>Description</summary>
    public string UserReviewTextPlaceholder => Get("USER_REVIEW_TEXT_PLACEHOLDER");

    /// <summary>Sorry my work didn’t hit the mark! I’d love to know what went wrong so I can make it better.</summary>
    public string UserReviewSorryMsg => Get("USER_REVIEW_SORRY_MSG");

    /// <summary>I'm glad you liked my work!</summary>
    public string UserReviewGladMsg => Get("USER_REVIEW_GLAD_MSG");

    /// <summary>Thank you</summary>
    public string ThankYou => Get("THANK_YOU");

    /// <summary>Send</summary>
    public string Send => Get("SEND");

    /// <summary>System settings</summary>
    public string SystemSettings => Get("SYSTEM_SETTINGS");

    /// <summary>Open system settings</summary>
    public string OpenSystemSettings => Get("OPEN_SYSTEM_SETTINGS");

    /// <summary>Go premium and unlock more features.</summary>
    public string GoPremiumAndUnlockFeatures => Get("GO_PREMIUM_AND_UNLOCK_FEATURES");

    /// <summary>Turn off</summary>
    public string TurnOff => Get("TURN_OFF");

    /// <summary>Private and custom DNS</summary>
    public string PrivateAndCustomDns => Get("PRIVATE_AND_CUSTOM_DNS");

    /// <summary>Enhance your privacy by customizing your DNS for a more secure connection.</summary>
    public string PrivateAndCustomDnsDesc => Get("PRIVATE_AND_CUSTOM_DNS_DESC");

    /// <summary>Private &lt;span class="text-promote-premium-color-premium"&gt;DNS&lt;/span&gt;</summary>
    public string PrivateDnsColored => Get("PRIVATE_DNS_COLORED");

    /// <summary>It looks like Private DNS is active on your device. This feature is a premium because it interferes with ad delivery ...</summary>
    public string PrivateDnsDialogMsg => Get("PRIVATE_DNS_DIALOG_MSG");

    /// <summary>Turn off private DNS to continue for free.</summary>
    public string PrivateDnsTurnOffMsg => Get("PRIVATE_DNS_TURN_OFF_MSG");

    /// <summary>To turn off your private DNS, please follow these steps:</summary>
    public string PrivateDnsHowToTurnOffDesc => Get("PRIVATE_DNS_HOW_TO_TURN_OFF_DESC");

    /// <summary>If that doesn't solve the issue, there may be a problem with your network.</summary>
    public string PrivateDnsHowToTurnOffFinalDesc => Get("PRIVATE_DNS_HOW_TO_TURN_OFF_FINAL_DESC");

    /// <summary>Open your device's &lt;strong&gt;Settings&lt;/strong&gt;.</summary>
    public string PrivateDnsTurnOffStep1 => Get("PRIVATE_DNS_TURN_OFF_STEP_1");

    /// <summary>Tap the &lt;strong&gt;search&lt;/strong&gt; icon.</summary>
    public string PrivateDnsTurnOffStep2 => Get("PRIVATE_DNS_TURN_OFF_STEP_2");

    /// <summary>Type &lt;strong&gt;"DNS"&lt;/strong&gt; and select the &lt;strong&gt;Private DNS&lt;/strong&gt; option.</summary>
    public string PrivateDnsTurnOffStep3 => Get("PRIVATE_DNS_TURN_OFF_STEP_3");

    /// <summary>Select &lt;strong&gt;Off&lt;/strong&gt;.</summary>
    public string PrivateDnsTurnOffStep4 => Get("PRIVATE_DNS_TURN_OFF_STEP_4");

    /// <summary>Turn off private DNS</summary>
    public string TurnOffPrivateDns => Get("TURN_OFF_PRIVATE_DNS");

    /// <summary>Open your device's &lt;strong&gt;Settings&lt;/strong&gt;.</summary>
    public string PrivateDnsTurnOnStep1 => Get("PRIVATE_DNS_TURN_ON_STEP_1");

    /// <summary>Tap the &lt;strong&gt;search&lt;/strong&gt; icon.</summary>
    public string PrivateDnsTurnOnStep2 => Get("PRIVATE_DNS_TURN_ON_STEP_2");

    /// <summary>Type &lt;strong&gt;"DNS"&lt;/strong&gt; and select the &lt;strong&gt;Private DNS&lt;/strong&gt; option.</summary>
    public string PrivateDnsTurnOnStep3 => Get("PRIVATE_DNS_TURN_ON_STEP_3");

    /// <summary>Select &lt;strong&gt;Private DNS provider hostname&lt;/strong&gt;.</summary>
    public string PrivateDnsTurnOnStep4 => Get("PRIVATE_DNS_TURN_ON_STEP_4");

    /// <summary>Enter your desired DNS.</summary>
    public string PrivateDnsTurnOnStep5 => Get("PRIVATE_DNS_TURN_ON_STEP_5");

    /// <summary>Adapter DNS</summary>
    public string AdapterDns => Get("ADAPTER_DNS");

    /// <summary>Change the default DNS server by specifying your own.</summary>
    public string AdapterDnsDesc => Get("ADAPTER_DNS_DESC");

    /// <summary>Learn more</summary>
    public string LearnMore => Get("LEARN_MORE");

    /// <summary>Learn more about this issue</summary>
    public string LearnMoreAboutThisIssue => Get("LEARN_MORE_ABOUT_THIS_ISSUE");

    /// <summary>Free servers disruptions</summary>
    public string FreeServersDisruptions => Get("FREE_SERVERS_DISRUPTIONS");

    /// <summary>Not supported by server</summary>
    public string NotSupportedByServer => Get("NOT_SUPPORTED_BY_SERVER");

    /// <summary>Open VPN settings</summary>
    public string OpenVpnSettings => Get("OPEN_VPN_SETTINGS");

    /// <summary>DNS</summary>
    public string Dns => Get("DNS");

    /// <summary>Manage how website addresses are resolved by configuring Private DNS and Adapter DNS.</summary>
    public string DnsDesc => Get("DNS_DESC");

    /// <summary>Managed by VPN server.</summary>
    public string AdapterDnsAutoDesc => Get("ADAPTER_DNS_AUTO_DESC");

    /// <summary>Enter your own DNS server.</summary>
    public string AdapterDnsCustomDesc => Get("ADAPTER_DNS_CUSTOM_DESC");

    /// <summary>Please enter a valid IP address for DNS 1.</summary>
    public string Dns1Required => Get("DNS1_REQUIRED");

    /// <summary>Please enter a valid IPv4 or IPv6 address.</summary>
    public string InvalidIp => Get("INVALID_IP");

    /// <summary>Custom DNS was not saved because DNS 1 is missing or invalid.</summary>
    public string CustomDnsDiscarded => Get("CUSTOM_DNS_DISCARDED");

    /// <summary>Private DNS is currently active and may prevent custom DNS from being used.</summary>
    public string PrivateDnsAvailableAlertMsg => Get("PRIVATE_DNS_AVAILABLE_ALERT_MSG");

    /// <summary>VPN connection has been revoked by the system or another VPN app.</summary>
    public string VpnServiceRevokedMsg => Get("VPN_SERVICE_REVOKED_MSG");

    /// <summary>In use features</summary>
    public string InUseFeatures => Get("IN_USE_FEATURES");

    /// <summary>The following features are customized and may impact your connectivity.</summary>
    public string InUseFeaturesDesc => Get("IN_USE_FEATURES_DESC");

    /// <summary>Validating proxies</summary>
    public string ValidatingProxies => Get("VALIDATING_PROXIES");

    /// <summary>Connectivity</summary>
    public string Connectivity => Get("CONNECTIVITY");

    /// <summary>App Settings</summary>
    public string AppSettings => Get("APP_SETTINGS");

    /// <summary>Privacy &amp; Security</summary>
    public string PrivacyAndSecurity => Get("PRIVACY_AND_SECURITY");

    /// <summary>Privacy</summary>
    public string Privacy => Get("PRIVACY");

    /// <summary>Control anonymous usage data and read our privacy policy.</summary>
    public string PrivacyDesc => Get("PRIVACY_DESC");

    /// <summary>Privacy Policy</summary>
    public string PrivacyPolicy => Get("PRIVACY_POLICY");

    /// <summary>Terms of Use</summary>
    public string TermsOfUse => Get("TERMS_OF_USE");

    /// <summary>By tapping Accept and continue, you agree to:</summary>
    public string AcceptLicenseNotice => Get("ACCEPT_LICENSE_NOTICE");

    /// <summary>Scan this code with your phone's camera, or type the address below into a browser.</summary>
    public string ScanQrToOpen => Get("SCAN_QR_TO_OPEN");

    /// <summary>Remote Access</summary>
    public string RemoteAccess => Get("REMOTE_ACCESS");

    /// <summary>Manage VpnHood from your phone or computer: scan this code, or type the address into a browser on the same network.</summary>
    public string RemoteAccessDesc => Get("REMOTE_ACCESS_DESC");

    /// <summary>Other addresses:</summary>
    public string RemoteAccessOtherAddresses => Get("REMOTE_ACCESS_OTHER_ADDRESSES");

    /// <summary>Keep this open while you make changes. Remote access ends when you press Done or go back.</summary>
    public string RemoteAccessKeepOpen => Get("REMOTE_ACCESS_KEEP_OPEN");

    /// <summary>No device connected yet.</summary>
    public string RemoteAccessNoDevice => Get("REMOTE_ACCESS_NO_DEVICE");

    /// <summary>Connected from {address}.</summary>
    public string RemoteAccessConnectedFrom(object address) => Get("REMOTE_ACCESS_CONNECTED_FROM", ("address", address));

    /// <summary>On your phone, open Servers to add or remove servers.</summary>
    public string RemoteAccessHintServers => Get("REMOTE_ACCESS_HINT_SERVERS");

    /// <summary>On your phone, open Settings to change these.</summary>
    public string RemoteAccessHintSettings => Get("REMOTE_ACCESS_HINT_SETTINGS");

    /// <summary>You are managing your TV. Keep its Remote Access screen open while you make changes.</summary>
    public string ManagingTvBanner => Get("MANAGING_TV_BANNER");

    /// <summary>Continue on your TV</summary>
    public string ContinueOnTvTitle => Get("CONTINUE_ON_TV_TITLE");

    /// <summary>Finish this step on the TV screen. This page carries on by itself when it is done.</summary>
    public string ContinueOnTvDesc => Get("CONTINUE_ON_TV_DESC");

    /// <summary>Sign in on your phone</summary>
    public string SignInOnYourPhone => Get("SIGN_IN_ON_YOUR_PHONE");

    /// <summary>On your phone, open the menu and sign in.</summary>
    public string RemoteAccessHintSignIn => Get("REMOTE_ACCESS_HINT_SIGN_IN");

    /// <summary>On your phone</summary>
    public string ManageFromYourPhone => Get("MANAGE_FROM_YOUR_PHONE");

    /// <summary>Accept and continue</summary>
    public string AcceptAndContinue => Get("ACCEPT_AND_CONTINUE");

    /// <summary>Share anonymous usage data</summary>
    public string AllowAnonymousTracker => Get("ALLOW_ANONYMOUS_TRACKER");

    /// <summary>Help us improve the app by sending anonymous usage and diagnostic data.</summary>
    public string AllowAnonymousTrackerDesc => Get("ALLOW_ANONYMOUS_TRACKER_DESC");

    /// <summary>We never log your browsing activity, the sites you visit, or the content of your traffic. When this is on, the app se...</summary>
    public string AnonymousTrackerNotice => Get("ANONYMOUS_TRACKER_NOTICE");

    /// <summary>Enforced by the server</summary>
    public string EnforcedByServer => Get("ENFORCED_BY_SERVER");

    /// <summary>Enforced by the Split Domain settings</summary>
    public string EnforcedByDomainFilter => Get("ENFORCED_BY_DOMAIN_FILTER");

    /// <summary>Split Domain may not work properly because the server does not support Cloak Mode.</summary>
    public string DomainFilterServerNoCloak => Get("DOMAIN_FILTER_SERVER_NO_CLOAK");

    /// <summary>Why Do Free Servers Experience Disruptions?</summary>
    public string LearnMoreFreeServersDisruptions1 => Get("LEARN_MORE_FREE_SERVERS_DISRUPTIONS_1");

    /// <summary>Connection stability is a major challenge that both users and VPN service providers struggle with. Contrary to what s...</summary>
    public string LearnMoreFreeServersDisruptions2 => Get("LEARN_MORE_FREE_SERVERS_DISRUPTIONS_2");

    /// <summary>Automatic IP Detection Due to High User Density</summary>
    public string LearnMoreFreeServersDisruptions3 => Get("LEARN_MORE_FREE_SERVERS_DISRUPTIONS_3");

    /// <summary>Although VpnHood is equipped with DPI Proof (Deep Packet Inspection), free servers, due to their public nature, host ...</summary>
    public string LearnMoreFreeServersDisruptions4 => Get("LEARN_MORE_FREE_SERVERS_DISRUPTIONS_4");

    /// <summary>Differences in ISP-Level Filtering</summary>
    public string LearnMoreFreeServersDisruptions5 => Get("LEARN_MORE_FREE_SERVERS_DISRUPTIONS_5");

    /// <summary>Differences in the policies of Internet Service Providers (ISPs) cause users to have varying experiences. It is very ...</summary>
    public string LearnMoreFreeServersDisruptions6 => Get("LEARN_MORE_FREE_SERVERS_DISRUPTIONS_6");

    /// <summary>Regaining Access to Servers</summary>
    public string LearnMoreFreeServersDisruptions7 => Get("LEARN_MORE_FREE_SERVERS_DISRUPTIONS_7");

    /// <summary>Inability to connect to free servers is not a permanent condition. Filtering systems operate dynamically and in real ...</summary>
    public string LearnMoreFreeServersDisruptions8 => Get("LEARN_MORE_FREE_SERVERS_DISRUPTIONS_8");

    /// <summary>Final Recommendations</summary>
    public string LearnMoreFreeServersDisruptions9 => Get("LEARN_MORE_FREE_SERVERS_DISRUPTIONS_9");

    /// <summary>Frequent Updates:</summary>
    public string LearnMoreFreeServersDisruptions10 => Get("LEARN_MORE_FREE_SERVERS_DISRUPTIONS_10");

    /// <summary>Always use the latest version of the app to receive the newest server list.</summary>
    public string LearnMoreFreeServersDisruptions11 => Get("LEARN_MORE_FREE_SERVERS_DISRUPTIONS_11");

    /// <summary>Switch Internet Providers:</summary>
    public string LearnMoreFreeServersDisruptions12 => Get("LEARN_MORE_FREE_SERVERS_DISRUPTIONS_12");

    /// <summary>Switching between Wi‑Fi and mobile data can bypass local ISP restrictions.</summary>
    public string LearnMoreFreeServersDisruptions13 => Get("LEARN_MORE_FREE_SERVERS_DISRUPTIONS_13");

    /// <summary>Use Auto Location:</summary>
    public string LearnMoreFreeServersDisruptions14 => Get("LEARN_MORE_FREE_SERVERS_DISRUPTIONS_14");

    /// <summary>By selecting the Auto option in the location list, the app will find an accessible location and connect you to the mo...</summary>
    public string LearnMoreFreeServersDisruptions15 => Get("LEARN_MORE_FREE_SERVERS_DISRUPTIONS_15");

    /// <summary>Connect via Premium Servers:</summary>
    public string LearnMoreFreeServersDisruptions16 => Get("LEARN_MORE_FREE_SERVERS_DISRUPTIONS_16");

    /// <summary>Using the Try Premium option ensures that your ability to connect to any VPN server is not fully blocked. You can tem...</summary>
    public string LearnMoreFreeServersDisruptions17 => Get("LEARN_MORE_FREE_SERVERS_DISRUPTIONS_17");

    /// <summary>Code</summary>
    public string Code => Get("CODE");

    /// <summary>Try again</summary>
    public string TryAgain => Get("TRY_AGAIN");

    /// <summary>Auto refresh</summary>
    public string AutoRefresh => Get("AUTO_REFRESH");

    /// <summary>Exclude</summary>
    public string Exclude => Get("EXCLUDE");

    /// <summary>Could not get premium code.</summary>
    public string CouldNotGetPremiumCode => Get("COULD_NOT_GET_PREMIUM_CODE");

    /// <summary>Show code</summary>
    public string ShowCode => Get("SHOW_CODE");

    /// <summary>Hide code</summary>
    public string HideCode => Get("HIDE_CODE");

    /// <summary>Copy code</summary>
    public string CopyCode => Get("COPY_CODE");

    /// <summary>Use this code to get premium on your other devices.</summary>
    public string UseCodeOnOtherDevices => Get("USE_CODE_ON_OTHER_DEVICES");

    /// <summary>Could not get client profile id.</summary>
    public string CouldNotGetClientProfileId => Get("COULD_NOT_GET_CLIENT_PROFILE_ID");

    /// <summary>Remove current premium code</summary>
    public string RemoveCurrentPremiumCode => Get("REMOVE_CURRENT_PREMIUM_CODE");

    /// <summary>Remove this code from this device. The code itself is not invalidated and can be entered again.</summary>
    public string RemoveLocalPremiumCodeDesc => Get("REMOVE_LOCAL_PREMIUM_CODE_DESC");

    /// <summary>Renew premium</summary>
    public string ReNewPremium => Get("RE_NEW_PREMIUM");

    /// <summary>Exit premium</summary>
    public string ExitPremium => Get("EXIT_PREMIUM");

    /// <summary>Split Tunneling</summary>
    public string SplitTunneling => Get("SPLIT_TUNNELING");

    /// <summary>Choose what uses the VPN and what connects directly.</summary>
    public string SplitTunnelingDesc => Get("SPLIT_TUNNELING_DESC");

    /// <summary>Starlink Tools</summary>
    public string StarlinkTools => Get("STARLINK_TOOLS");

    /// <summary>This applies to {profileName} only.</summary>
    public string StarlinkToolsProfileScope(object profileName) => Get("STARLINK_TOOLS_PROFILE_SCOPE", ("profileName", profileName));

    /// <summary>Send the VPN traffic through a Starlink connection. Tell the app where that Starlink is.</summary>
    public string StarlinkToolsDesc => Get("STARLINK_TOOLS_DESC");

    /// <summary>Off</summary>
    public string StarlinkModeDisabled => Get("STARLINK_MODE_DISABLED");

    /// <summary>Don't use a Starlink relay. Connect directly to the VPN server.</summary>
    public string StarlinkModeDisabledDesc => Get("STARLINK_MODE_DISABLED_DESC");

    /// <summary>Remote Starlink</summary>
    public string StarlinkModeRemote => Get("STARLINK_MODE_REMOTE");

    /// <summary>The Starlink is somewhere else.</summary>
    public string StarlinkModeRemoteDesc => Get("STARLINK_MODE_REMOTE_DESC");

    /// <summary>Local Starlink</summary>
    public string StarlinkModeLocal => Get("STARLINK_MODE_LOCAL");

    /// <summary>The Starlink relay is on the same Wi-Fi / LAN as this device. Let the app find it, or enter its address.</summary>
    public string StarlinkModeLocalDesc => Get("STARLINK_MODE_LOCAL_DESC");

    /// <summary>Auto Find</summary>
    public string StarlinkAutoFind => Get("STARLINK_AUTO_FIND");

    /// <summary>Find</summary>
    public string StarlinkFind => Get("STARLINK_FIND");

    /// <summary>Not implemented yet.</summary>
    public string NotImplementedYet => Get("NOT_IMPLEMENTED_YET");

    /// <summary>Restore premium</summary>
    public string RestorePremium => Get("RESTORE_PREMIUM");

    /// <summary>This code expired on {date}. It is kept — if it is extended, it will work again by itself.</summary>
    public string CodeRefusedExpiredNotice(object date) => Get("CODE_REFUSED_EXPIRED_NOTICE", ("date", date));

    /// <summary>The server rejected this code on {date}. It is kept and will work again if its issuer restores it.</summary>
    public string CodeRefusedRejectedNotice(object date) => Get("CODE_REFUSED_REJECTED_NOTICE", ("date", date));

    /// <summary>Exit</summary>
    public string Exit => Get("EXIT");

    /// <summary>Manage</summary>
    public string Manage => Get("MANAGE");

    /// <summary>Open</summary>
    public string Open => Get("OPEN");

    /// <summary>{0} Access key has been added.</summary>
    public string MsgAccessKeyAdded => Get("MSG_ACCESS_KEY_ADDED");

    /// <summary>{0} access key has been updated.</summary>
    public string MsgAccessKeyUpdated => Get("MSG_ACCESS_KEY_UPDATED");

    /// <summary>Could not read the access key.</summary>
    public string MsgCantReadAccessKey => Get("MSG_CANT_READ_ACCESS_KEY");

    /// <summary>Unsupported file type.</summary>
    public string MsgUnsupportedContent => Get("MSG_UNSUPPORTED_CONTENT");

    /// <summary>This server requires a display Ad but could not display it.</summary>
    public string MsgCantShowAd => Get("MSG_CANT_SHOW_AD");
}
