<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Description>Provides packet-level domain filtering usig SNI.</Description>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Filtering.Abstractions\VpnHood.Core.Filtering.Abstractions.csproj" />
		<ProjectReference Include="..\..\Packets\VpnHood.Core.Packets.csproj" />
	</ItemGroup>

</Project>