# Brings the web UI's palette here: reads theme/colors.ts (the tones) and theme/themes.ts (the two
# themes, the same keys with two sets of values) from VpnHood.Client.WebUI and writes
# Colors.axaml, BlueTheme.g.axaml and VioletTheme.g.axaml - one Color per tone, one brush per
# theme key, named by the key in PascalCase plus "Brush": 'on-config-btn-bg' is
# OnConfigBtnBgBrush. A page ported from the web UI names the key it named there, and a key added
# there arrives here by running this. The hand-written BlueTheme.axaml and VioletTheme.axaml
# merge these and add what the web UI writes as CSS rather than as a key: a gradient, an alpha.
#
# A "tonal" brush is also written for the keys the web UI uses with Vuetify's tonal variant - the
# colour at 16% - because a brush cannot take its alpha from another brush in XAML.
#
# Run with pwsh: Windows PowerShell would read these files as ANSI.

$ErrorActionPreference = "Stop";

# This repo's root is the folder holding VpnHood.slnx, and <Vh> - where VpnHood and
# VpnHood.Client.WebUI sit side by side - is its parent. Found, not counted, so moving this
# project does not silently point the lookup at the wrong folder.
$projectDir = Split-Path -Parent $PSScriptRoot;
$repoDir = $PSScriptRoot;
while ($repoDir -and -not (Test-Path (Join-Path $repoDir "VpnHood.slnx"))) { $repoDir = Split-Path -Parent $repoDir; }
if (-not $repoDir) { throw "Could not find VpnHood.slnx above $PSScriptRoot"; }
$vhFolder = Split-Path -Parent $repoDir;
$themeDir = Join-Path $vhFolder "VpnHood.Client.WebUI\src\theme";
if (!(Test-Path $themeDir)) { throw "The web UI's theme is not beside this repo. $themeDir"; }

$utf8 = New-Object System.Text.UTF8Encoding($false);
$utf8Bom = New-Object System.Text.UTF8Encoding($true);

# the keys the web UI paints with variant="tonal": the colour as text over the colour at 16%
$tonalKeys = @(
    "btn-style-2", "btn-style-4", "btn-style-5", "highlight", "active", "error", "warning", "enable-premium",
    "switch-btn", "tonal-icon-btn", "dialog-alert-btn", "go-premium-btn", "count-down-normal",
    "count-down-alert", "count-down-warning", "rate-icon", "premium-code-btn", "info", "on-note",
    "on-general-dialog", "update-snackbar-alert", "update-snackbar-warning", "btn-on-update-snackbar");

function ToPascal([string] $key) {
    $parts = $key -split "-";
    return ($parts | ForEach-Object { $_.Substring(0, 1).ToUpperInvariant() + $_.Substring(1) }) -join "";
}

# CSS writes #RRGGBBAA; Avalonia reads #AARRGGBB
function ToAvaloniaColor([string] $css) {
    $hex = $css.TrimStart("#");
    if ($hex.Length -eq 8) { return "#" + $hex.Substring(6, 2) + $hex.Substring(0, 6); }
    return "#" + $hex;
}

# ---- colors.ts: the tones ----
$colors = @{};   # "Purple500" -> "#150e3d"
$colorOrder = New-Object System.Collections.Generic.List[string];
$group = $null;
foreach ($line in [System.IO.File]::ReadAllLines((Join-Path $themeDir "colors.ts"), $utf8)) {
    if ($line -match '^\s*(\w+):\s*\{') { $group = $Matches[1]; continue; }
    if ($line -match '^\s*(\d+):\s*"(#[0-9a-fA-F]+)"') {
        $name = (ToPascal $group) + $Matches[1];
        $colors[$name] = ToAvaloniaColor $Matches[2];
        $colorOrder.Add($name);
    }
}

$sb = New-Object System.Text.StringBuilder;
[void]$sb.AppendLine('<ResourceDictionary xmlns="https://github.com/avaloniaui"');
[void]$sb.AppendLine('                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">');
[void]$sb.AppendLine('');
[void]$sb.AppendLine('  <!-- Generated by _sync-theme.ps1 from the web UI''s theme/colors.ts: its tones, which only the');
[void]$sb.AppendLine('       two theme files read. A view names a theme key, never a tone, which is what lets the same');
[void]$sb.AppendLine('       view paint in either product. -->');
[void]$sb.AppendLine('');
foreach ($name in $colorOrder) { [void]$sb.AppendLine("  <Color x:Key=""$name"">$($colors[$name])</Color>"); }
[void]$sb.AppendLine('');
[void]$sb.AppendLine('</ResourceDictionary>');
[System.IO.File]::WriteAllText((Join-Path $PSScriptRoot "Colors.axaml"), $sb.ToString(), $utf8Bom);
Write-Host "Colors.axaml: $($colorOrder.Count) tones.";

# ---- themes.ts: the two themes ----
$themesText = [System.IO.File]::ReadAllText((Join-Path $themeDir "themes.ts"), $utf8);

function WriteTheme([string] $variable, [string] $fileName, [string] $theme) {
    $start = $themesText.IndexOf("export const $variable");
    if ($start -lt 0) { throw "themes.ts has no $variable."; }
    $end = $themesText.IndexOf("satisfies ThemeColorNames", $start);
    $block = $themesText.Substring($start, $end - $start);

    $sb = New-Object System.Text.StringBuilder;
    [void]$sb.AppendLine('<ResourceDictionary xmlns="https://github.com/avaloniaui"');
    [void]$sb.AppendLine('                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">');
    [void]$sb.AppendLine('');
    [void]$sb.AppendLine("  <!-- Generated by _sync-theme.ps1 from the web UI's $variable (theme/themes.ts): the $theme");
    [void]$sb.AppendLine('       theme, key for key. Edit the web UI''s theme and run the script; do not edit this file. -->');
    [void]$sb.AppendLine('');
    [void]$sb.AppendLine('  <!-- the tones these brushes name, so this file stands on its own -->');
    [void]$sb.AppendLine('  <ResourceDictionary.MergedDictionaries>');
    [void]$sb.AppendLine('    <ResourceInclude Source="avares://VpnHood.AppUi.Presentation.Classic.Avalonia/Styles/Colors.axaml" />');
    [void]$sb.AppendLine('  </ResourceDictionary.MergedDictionaries>');
    [void]$sb.AppendLine('');

    $count = 0;
    foreach ($line in $block -split "`n") {
        if ($line -notmatch "^\s*'?([a-z0-9-]+)'?\s*:\s*(myColors\.(\w+)\['(\d+)'\]|'(#[0-9a-fA-F]+)')") { continue; }
        $key = $Matches[1];
        $name = (ToPascal $key) + "Brush";
        if ($Matches[3]) {
            $tone = (ToPascal $Matches[3]) + $Matches[4];
            if (!$colors.ContainsKey($tone)) { throw "themes.ts names a tone colors.ts has not: $tone"; }
            [void]$sb.AppendLine("  <SolidColorBrush x:Key=""$name"" Color=""{StaticResource $tone}"" />");
            $hex = $colors[$tone];
        }
        else {
            $hex = ToAvaloniaColor $Matches[5];
            [void]$sb.AppendLine("  <SolidColorBrush x:Key=""$name"" Color=""$hex"" />");
        }
        if ($tonalKeys -contains $key) {
            $rgb = $hex.TrimStart("#");
            if ($rgb.Length -eq 8) { $rgb = $rgb.Substring(2); }
            [void]$sb.AppendLine("  <SolidColorBrush x:Key=""$((ToPascal $key))TonalBrush"" Color=""#29$rgb"" />");
        }
        $count++;
    }

    [void]$sb.AppendLine('');
    [void]$sb.AppendLine('</ResourceDictionary>');
    [System.IO.File]::WriteAllText((Join-Path $PSScriptRoot $fileName), $sb.ToString(), $utf8Bom);
    Write-Host "${fileName}: $count keys.";
}

WriteTheme "vhBlueThemeColors" "BlueTheme.g.axaml" "blue";
WriteTheme "vhVioletThemeColors" "VioletTheme.g.axaml" "violet";
