<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Description>VpnHood client device provider for Linux</Description>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VpnHood.Core.Client.Devices.Abstractions\VpnHood.Core.Client.Devices.Abstractions.csproj" />
    <ProjectReference Include="..\VpnHood.Core.Client.VpnServices.Host\VpnHood.Core.Client.VpnServices.Host.csproj" />
    <ProjectReference Include="..\..\Net\VpnHood.Net.Quic.MsQuic\VpnHood.Net.Quic.MsQuic.csproj" />
    <ProjectReference Include="..\..\Net\VpnHood.Net.VpnAdapters.LinuxTun\VpnHood.Net.VpnAdapters.LinuxTun.csproj" />
  </ItemGroup>

</Project>
