<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-android36.1</TargetFramework>
		<SupportedOSPlatformVersion>24</SupportedOSPlatformVersion>
		<RootNamespace>VpnHood.AppUi.Hosting.Avalonia.Droid</RootNamespace>
		<Description>Hosts the VpnHood Avalonia UI in an Android activity</Description>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia.Android" Version="12.1.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Avalonia\VpnHood.AppUi.Hosting.Avalonia.csproj" />
		<ProjectReference Include="..\..\..\..\AppLib\App\App.Android\VpnHood.AppLib.App.Android.csproj" />
	</ItemGroup>
</Project>
