# Brings the web UI's words here: copies every locale file from VpnHood.Client.WebUI (en.json the
# source a person edits, the rest vhtranslator's) into Assets/Locales, and writes Strings.g.cs -
# one member per key of en.json, so a page names a string in C# and a key that disappears is a
# compile error. Run it after the translator has run, or after a key is added to en.json.
#
# Every file is read and written with an explicit UTF-8 encoding: Windows PowerShell would
# otherwise read these files as ANSI and double-encode every non-ASCII word in them.

$ErrorActionPreference = "Stop";

# <Vh>/VpnHood/src/AppLib/VpnHood.AppLib.AvaloniaUI/Resources -> <Vh>
$projectDir = Split-Path -Parent $PSScriptRoot;
$vhFolder = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $projectDir)));
$localesDir = Join-Path $vhFolder "VpnHood.Client.WebUI\src\locales";
$assetsDir = Join-Path $projectDir "Assets\Locales";
$outputFile = Join-Path $PSScriptRoot "Strings.g.cs";

if (!(Test-Path $localesDir)) { throw "The web UI's locales are not beside this repo. $localesDir"; }

# the locale files, verbatim: a copy, never a conversion, so both UIs read the same words
New-Item -ItemType Directory -Force -Path $assetsDir | Out-Null;
Get-ChildItem (Join-Path $assetsDir "*.json") | Remove-Item;
$files = Get-ChildItem (Join-Path $localesDir "*.json");
foreach ($file in $files) { Copy-Item $file.FullName (Join-Path $assetsDir $file.Name) -Force; }
Write-Host "Copied $($files.Count) locale files to Assets\Locales.";

# one member per key of en.json
$utf8 = New-Object System.Text.UTF8Encoding($false);
$english = [System.IO.File]::ReadAllText((Join-Path $assetsDir "en.json"), $utf8) | ConvertFrom-Json;

function Get-MemberName([string] $key) {
    $name = ($key -split "_" | ForEach-Object {
        if ($_.Length -eq 0) { "" }
        else { $_.Substring(0, 1).ToUpperInvariant() + $_.Substring(1).ToLowerInvariant() }
    }) -join "";
    # a key may start with a digit (24_7_SUPPORT); a member may not
    if ($name -match "^\d") { $name = "_" + $name; }
    return $name;
}

function Get-DocText([string] $text) {
    $line = ($text -replace "\s+", " ").Trim();
    if ($line.Length -gt 120) { $line = $line.Substring(0, 117) + "..."; }
    return $line.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}

$builder = New-Object System.Text.StringBuilder;
[void]$builder.AppendLine("// <auto-generated>");
[void]$builder.AppendLine("//     Written by _sync-locales.ps1 from Assets/Locales/en.json. Do not edit by hand:");
[void]$builder.AppendLine("//     the words live in the web UI's locale files, and this file follows them.");
[void]$builder.AppendLine("// </auto-generated>");
[void]$builder.AppendLine("");
[void]$builder.AppendLine("namespace VpnHood.AppLib.AvaloniaUI.Resources;");
[void]$builder.AppendLine("");
[void]$builder.AppendLine("public sealed partial class Strings");
[void]$builder.AppendLine("{");

$names = @{};
$count = 0;
foreach ($property in $english.PSObject.Properties) {
    $key = $property.Name;
    $text = [string]$property.Value;
    $name = Get-MemberName $key;
    if ($names.ContainsKey($name)) { throw "Two keys make the same member name '$name': '$key' and '$($names[$name])'."; }
    $names[$name] = $key;

    # vue-i18n's named placeholders, in the order the text uses them
    $placeholders = @();
    foreach ($match in [regex]::Matches($text, "{([A-Za-z][A-Za-z0-9]*)}")) {
        if ($placeholders -notcontains $match.Groups[1].Value) { $placeholders += $match.Groups[1].Value; }
    }

    if ($count -gt 0) { [void]$builder.AppendLine(""); }
    [void]$builder.AppendLine("    /// <summary>$(Get-DocText $text)</summary>");
    if ($placeholders.Count -eq 0) {
        [void]$builder.AppendLine("    public string $name => Get(`"$key`");");
    }
    else {
        $parameters = ($placeholders | ForEach-Object { "object $_" }) -join ", ";
        $arguments = ($placeholders | ForEach-Object { "(`"$_`", $_)" }) -join ", ";
        [void]$builder.AppendLine("    public string $name($parameters) => Get(`"$key`", $arguments);");
    }
    $count++;
}

[void]$builder.AppendLine("}");
[System.IO.File]::WriteAllText($outputFile, $builder.ToString(), (New-Object System.Text.UTF8Encoding($true)));
Write-Host "Wrote $count members to Strings.g.cs.";
