// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VpnHood.AccessServer.Models;

namespace VpnHood.AccessServer2.Migrations
{
    [DbContext(typeof(VhContext))]
    [Migration("20210724023327_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Latin1_General_100_CS_AS_SC_UTF8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VpnHood.AccessServer.Models.AccessToken", b =>
                {
                    b.Property<Guid>("AccessTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AccessTokenName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<int>("Lifetime")
                        .HasColumnType("int");

                    b.Property<int>("MaxClient")
                        .HasColumnType("int");

                    b.Property<long>("MaxTraffic")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Secret")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("binary(16)")
                        .HasDefaultValueSql("(Crypt_Gen_Random((16)))")
                        .IsFixedLength(true);

                    b.Property<int>("ServerEndPointGroupId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<int>("SupportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AccessTokenId");

                    b.HasIndex("ServerEndPointGroupId");

                    b.HasIndex("SupportId")
                        .IsUnique();

                    b.ToTable("AccessTokens");
                });

            modelBuilder.Entity("VpnHood.AccessServer.Models.AccessUsage", b =>
                {
                    b.Property<Guid>("AccessTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("CycleReceivedTraffic")
                        .HasColumnType("bigint");

                    b.Property<long>("CycleSentTraffic")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalReceivedTraffic")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalSentTraffic")
                        .HasColumnType("bigint");

                    b.HasKey("AccessTokenId", "ClientIp");

                    b.ToTable("AccessUsages");
                });

            modelBuilder.Entity("VpnHood.AccessServer.Models.Client", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientVersion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("LastConnectTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("VpnHood.AccessServer.Models.PublicCycle", b =>
                {
                    b.Property<string>("PublicCycleId")
                        .HasMaxLength(12)
                        .HasColumnType("nchar(12)")
                        .IsFixedLength(true);

                    b.HasKey("PublicCycleId");

                    b.ToTable("PublicCycles");
                });

            modelBuilder.Entity("VpnHood.AccessServer.Models.Server", b =>
                {
                    b.Property<Guid>("ServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LastSessionCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastStatusTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ServerName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ServerId");

                    b.HasIndex("ServerName")
                        .IsUnique()
                        .HasFilter("[ServerName] IS NOT NULL");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("VpnHood.AccessServer.Models.ServerEndPoint", b =>
                {
                    b.Property<string>("ServerEndPointId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("CertificateRawData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("ServerEndPointGroupId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ServerEndPointId");

                    b.HasIndex("ServerId");

                    b.HasIndex("ServerEndPointGroupId", "IsDefault")
                        .IsUnique()
                        .HasFilter("IsDefault = 1");

                    b.ToTable("ServerEndPoints");
                });

            modelBuilder.Entity("VpnHood.AccessServer.Models.ServerEndPointGroup", b =>
                {
                    b.Property<int>("ServerEndPointGroupId")
                        .HasColumnType("int");

                    b.Property<string>("ServerEndPointGroupName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ServerEndPointGroupId");

                    b.HasIndex("ServerEndPointGroupName")
                        .IsUnique()
                        .HasFilter("[ServerEndPointGroupName] IS NOT NULL");

                    b.ToTable("ServerEndPointGroups");
                });

            modelBuilder.Entity("VpnHood.AccessServer.Models.Setting", b =>
                {
                    b.Property<int>("SettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<bool>("IsProduction")
                        .HasColumnType("bit");

                    b.HasKey("SettingsId");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("VpnHood.AccessServer.Models.UsageLog", b =>
                {
                    b.Property<long>("UsageLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("AccessTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ClientVersion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("CycleReceivedTraffic")
                        .HasColumnType("bigint");

                    b.Property<long>("CycleSentTraffic")
                        .HasColumnType("bigint");

                    b.Property<long>("ReceivedTraffic")
                        .HasColumnType("bigint");

                    b.Property<long>("SentTraffic")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalReceivedTraffic")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalSentTraffic")
                        .HasColumnType("bigint");

                    b.HasKey("UsageLogId");

                    b.HasIndex("ClientId");

                    b.ToTable("UsageLogs");
                });

            modelBuilder.Entity("VpnHood.AccessServer.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthUserId")
                        .HasMaxLength(40)
                        .HasColumnType("nchar(40)")
                        .IsFixedLength(true);

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VpnHood.AccessServer.Models.AccessToken", b =>
                {
                    b.HasOne("VpnHood.AccessServer.Models.ServerEndPointGroup", "ServerEndPointGroup")
                        .WithMany("AccessTokens")
                        .HasForeignKey("ServerEndPointGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ServerEndPointGroup");
                });

            modelBuilder.Entity("VpnHood.AccessServer.Models.AccessUsage", b =>
                {
                    b.HasOne("VpnHood.AccessServer.Models.AccessToken", "AccessToken")
                        .WithMany("AccessUsages")
                        .HasForeignKey("AccessTokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessToken");
                });

            modelBuilder.Entity("VpnHood.AccessServer.Models.ServerEndPoint", b =>
                {
                    b.HasOne("VpnHood.AccessServer.Models.ServerEndPointGroup", "ServerEndPointGroup")
                        .WithMany("ServerEndPoints")
                        .HasForeignKey("ServerEndPointGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VpnHood.AccessServer.Models.Server", "Server")
                        .WithMany("ServerEndPoints")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Server");

                    b.Navigation("ServerEndPointGroup");
                });

            modelBuilder.Entity("VpnHood.AccessServer.Models.UsageLog", b =>
                {
                    b.HasOne("VpnHood.AccessServer.Models.Client", "Client")
                        .WithMany("UsageLogs")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("VpnHood.AccessServer.Models.AccessToken", b =>
                {
                    b.Navigation("AccessUsages");
                });

            modelBuilder.Entity("VpnHood.AccessServer.Models.Client", b =>
                {
                    b.Navigation("UsageLogs");
                });

            modelBuilder.Entity("VpnHood.AccessServer.Models.Server", b =>
                {
                    b.Navigation("ServerEndPoints");
                });

            modelBuilder.Entity("VpnHood.AccessServer.Models.ServerEndPointGroup", b =>
                {
                    b.Navigation("AccessTokens");

                    b.Navigation("ServerEndPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
