<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable>false</IsPackable>	<!-- application, not a NuGet package -->
		<Description>Shared Code between client apps</Description>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="VpnHood.Core.IpLocations.Assets.Ip2LocationLite" Version="8.2.852" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\AppLib\VpnHood.AppLib.App\VpnHood.AppLib.App.csproj" />
		<ProjectReference Include="..\..\AppLib\VpnHood.AppLib.Api.WebHost\VpnHood.AppLib.Api.WebHost.csproj" />
	</ItemGroup>


</Project>
