<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Description>Establish a connection to a VpnHood server. If you need to create a VpnApp client, we recommend using VpnHood.AppLib</Description>
		<OutputType>Library</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="VpnHood.Test" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Client.Abstractions\VpnHood.Core.Client.Abstractions.csproj" />
		<ProjectReference Include="..\..\Filtering\Filtering.Abstractions\VpnHood.Core.Filtering.Abstractions.csproj" />
		<ProjectReference Include="..\..\Filtering\Filtering.DomainFiltering\VpnHood.Core.Filtering.DomainFiltering.csproj" />
		<ProjectReference Include="..\..\Proxies\Proxies.Management.Abstractions\VpnHood.Core.Proxies.Management.Abstractions.csproj" />
		<ProjectReference Include="..\..\TcpStack\TcpStack\VpnHood.Core.TcpStack.csproj" />
		<ProjectReference Include="..\..\Tunneling\VpnHood.Core.Tunneling.csproj" />
		<ProjectReference Include="..\..\VpnAdapters\VpnAdapters.Abstractions\VpnHood.Core.VpnAdapters.Abstractions.csproj" />
	</ItemGroup>

</Project>
