<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Description>Establish a connection to a VpnHood server. If you need to create a VpnApp client, we recommend using VpnHood.AppLib</Description>
		<OutputType>Library</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="VpnHood.Test" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\VpnHood.Core.Client.Abstractions\VpnHood.Core.Client.Abstractions.csproj" />
		<ProjectReference Include="..\VpnHood.Core.Filtering.Abstractions\VpnHood.Core.Filtering.Abstractions.csproj" />
		<ProjectReference Include="..\VpnHood.Core.Filtering.DomainFiltering\VpnHood.Core.Filtering.DomainFiltering.csproj" />
		<ProjectReference Include="..\VpnHood.Core.Proxies.Management.Abstractions\VpnHood.Core.Proxies.Management.Abstractions.csproj" />
		<ProjectReference Include="..\..\Net\VpnHood.Net.TcpStack\VpnHood.Net.TcpStack.csproj" />
		<ProjectReference Include="..\VpnHood.Core.Tunneling\VpnHood.Core.Tunneling.csproj" />
		<ProjectReference Include="..\..\Net\VpnHood.Net.VpnAdapters.Abstractions\VpnHood.Net.VpnAdapters.Abstractions.csproj" />
	</ItemGroup>

</Project>
