# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Description of what the lane does"
  lane :playstore do
    # add actions here: https://docs.fastlane.tools/actions
    upload_to_play_store(
        skip_upload_apk: 'true',
        skip_upload_aab: 'true',
        skip_upload_changelogs: 'true',
        sync_image_upload: 'true'
        )
  end
end
