<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Description>VpnHood VpnAdapter for LinuxTun</Description>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\VpnHood.Net.VpnAdapters.Abstractions\VpnHood.Net.VpnAdapters.Abstractions.csproj" />
		<InternalsVisibleTo Include="VpnHood.Test" />
	</ItemGroup>

</Project>
