services:
  vpnhoodserver:
    image: vpnhood/vpnhoodserver
    container_name: VpnHoodServer
    network_mode: "host"
    restart: always
    stop_grace_period: 30s
    volumes:
        - /opt/VpnHoodServer/storage:/app/storage
